"""Regenerate saturn/renderer/_glsl.py from the editable .glsl sources.

The wheel excludes every .glsl file, and gl.py only falls back to the
embedded copy when the checkout file is absent, so rerun this after
editing wave.glsl or effects.glsl:

    python gen_glsl.py
"""
from pathlib import Path

RENDERER = Path(__file__).parent / "saturn" / "renderer"
SOURCES = ("wave.glsl", "effects.glsl")

HEADER = '"""Embedded copies of the renderer GLSL, generated by gen_glsl.py.\n\nDo not edit; the build excludes .glsl files and wheels load these when\nthe checkout sources are absent. Rerun `python gen_glsl.py` after edits.\n"""\n\nSOURCES = {}\n'


def main():
    blocks = []
    for name in SOURCES:
        text = (RENDERER / name).read_text(encoding="utf-8")
        blocks.append(f'SOURCES[{name!r}] = {text!r}\n')
    out = RENDERER / "_glsl.py"
    out.write_text(HEADER + "\n".join(blocks), encoding="utf-8", newline="\n")
    print(f"wrote {out.relative_to(Path(__file__).parent)} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
