// Adapted from Orb, https://github.com/LerSent001/orb
// Copyright (c) 2026 LerSent001. MIT License: ORB-LICENSE.txt.
// Generated by tools/port_orb_shaders.py; edit the converter to regenerate.
uniform float orb_speed;
uniform float orb_radius;
uniform float orb_zoom;
uniform float orb_warp;
uniform float orb_ridgeAmt;
uniform float orb_sharp;
uniform float orb_shade;
uniform float orb_sheen;
uniform float orb_gloss;
uniform float orb_shellMidAlpha;
uniform float orb_shellEdgeAlpha;
uniform float orb_exposure;
uniform float orb_style;
uniform float orb_edgeSoftness;
uniform float orb_edgeGlow;
uniform float orb_paletteCount;
uniform float orb_glassEnabled;
uniform float orb_glassOpacity;
uniform float orb_contourDeform;
uniform float orb_bandDensity;
uniform float orb_chromaticShift;
uniform float orb_metalScale;
uniform float orb_metalStretch;
uniform float orb_metalAngle;
uniform float orb_metalOffset;
uniform float orb_metalPhase;
uniform float orb_metalEvolution;
uniform float orb_metalRoughness;
uniform float orb_metalDepth;
uniform float orb_particleDensity;
uniform float orb_ribbonCount;
uniform float orb_ribbonWidth;
uniform float orb_ribbonTwist;
uniform float orb_ribbonFold;
uniform float orb_ribbonBreath;
uniform float orb_particleSize;
uniform float orb_particleBloom;
uniform vec4 orb_colorA;
uniform vec4 orb_colorB;
uniform vec4 orb_colorC;
uniform vec4 orb_colorD;
uniform vec4 orb_highlightColor;
uniform vec4 orb_shellInner;
uniform vec4 orb_shellMid;
uniform vec4 orb_shellEdge;
uniform vec4 orb_sheenColor;
uniform vec4 orb_specColor;
uniform vec4 orb_canvasColor;
uniform vec4 orb_glowColor;
uniform vec4 orb_paletteStop0;
uniform vec4 orb_paletteStop1;
uniform vec4 orb_paletteStop2;
uniform vec4 orb_paletteStop3;
uniform vec4 orb_paletteStop4;
uniform vec4 orb_paletteStop5;
uniform vec4 orb_paletteStop6;
uniform vec4 orb_paletteStop7;
uniform vec4 orb_paletteStop8;
uniform vec4 orb_paletteStop9;
uniform vec4 orb_paletteStop10;
uniform vec4 orb_paletteStop11;
struct Uniforms {
    vec2 size;
    float time;
    float speed;
    float radius;
    float zoom;
    float warp;
    float ridgeAmt;
    float sharp;
    float shade;
    float sheen;
    float gloss;
    float shellMidAlpha;
    float shellEdgeAlpha;
    float exposure;
    float style;
    float edgeSoftness;
    float edgeGlow;
    float paletteCount;
    float glassEnabled;
    float glassOpacity;
    float contourDeform;
    float bandDensity;
    float chromaticShift;
    float metalScale;
    float metalStretch;
    float metalAngle;
    float metalOffset;
    float metalPhase;
    float metalEvolution;
    float metalRoughness;
    float metalDepth;
    float particleDensity;
    float ribbonCount;
    float ribbonWidth;
    float ribbonTwist;
    float ribbonFold;
    float ribbonBreath;
    float particleSize;
    float particleBloom;
    vec4 colorA;
    vec4 colorB;
    vec4 colorC;
    vec4 colorD;
    vec4 highlightColor;
    vec4 shellInner;
    vec4 shellMid;
    vec4 shellEdge;
    vec4 sheenColor;
    vec4 specColor;
    vec4 canvasColor;
    vec4 glowColor;
    vec4 paletteStop0_;
    vec4 paletteStop1_;
    vec4 paletteStop2_;
    vec4 paletteStop3_;
    vec4 paletteStop4_;
    vec4 paletteStop5_;
    vec4 paletteStop6_;
    vec4 paletteStop7_;
    vec4 paletteStop8_;
    vec4 paletteStop9_;
    vec4 paletteStop10_;
    vec4 paletteStop11_;
};
Uniforms orbUniforms() { return Uniforms(u_resolution, u_time, orb_speed, orb_radius, orb_zoom, orb_warp, orb_ridgeAmt, orb_sharp, orb_shade, orb_sheen, orb_gloss, orb_shellMidAlpha, orb_shellEdgeAlpha, orb_exposure, orb_style, orb_edgeSoftness, orb_edgeGlow, orb_paletteCount, orb_glassEnabled, orb_glassOpacity, orb_contourDeform, orb_bandDensity, orb_chromaticShift, orb_metalScale, orb_metalStretch, orb_metalAngle, orb_metalOffset, orb_metalPhase, orb_metalEvolution, orb_metalRoughness, orb_metalDepth, orb_particleDensity, orb_ribbonCount, orb_ribbonWidth, orb_ribbonTwist, orb_ribbonFold, orb_ribbonBreath, orb_particleSize, orb_particleBloom, orb_colorA, orb_colorB, orb_colorC, orb_colorD, orb_highlightColor, orb_shellInner, orb_shellMid, orb_shellEdge, orb_sheenColor, orb_specColor, orb_canvasColor, orb_glowColor, orb_paletteStop0, orb_paletteStop1, orb_paletteStop2, orb_paletteStop3, orb_paletteStop4, orb_paletteStop5, orb_paletteStop6, orb_paletteStop7, orb_paletteStop8, orb_paletteStop9, orb_paletteStop10, orb_paletteStop11); }
struct MfRamp {
    float n;

    vec3 s0_;
    vec3 s1_;
    vec3 s2_;
    vec3 s3_;
    vec3 s4_;
    vec3 s5_;
    vec3 s6_;
    vec3 s7_;
    vec3 s8_;
    vec3 s9_;
    vec3 s10_;
    vec3 s11_;
};
const float GL_FU = 0.8817204;
const float GL_BSIG_CLEAR = 0.018;
const float GL_BSIG_GLASS = 0.0399;
const float GL_KA = 6.0;
const float GL_KG = 4.1209;
const float GL_KWA = 0.5;
const float GL_KR = 0.32;
const float GL_GH = 1.7320508;
const float GL_CLEAR_EA = 0.995;
const float GL_CLEAR_EB = 1.04;

float mfEdgeD(
    float soft
) {
    return soft - 0.005;
}

vec3 mfEdgeGlow(
    vec3 col,
    vec2 uv,
    vec2 ctr,
    float rad,
    float soft_1,
    float glow,
    vec3 glowRGB
) {
    if (glow <= 0.0) {
        return col;
    }
    float r_3 = length(uv - ctr);
    float outside = smoothstep(rad - max(soft_1, 0.0005), rad + max(soft_1, 0.0005), r_3);
    return col + (glowRGB * ((glow * exp(-(max(r_3 - rad, 0.0)) * 11.0)) * outside));
}

vec3 mfRampPick(
    float idx,
    vec3 s0_,
    vec3 s1_,
    vec3 s2_,
    vec3 s3_,
    vec3 s4_,
    vec3 s5_,
    vec3 s6_,
    vec3 s7_,
    vec3 s8_,
    vec3 s9_,
    vec3 s10_,
    vec3 s11_
) {
    vec3 r = vec3(0);
    r = s0_;
    vec3 _e14 = r;
    r = (idx == 1.0) ? s1_ : _e14;
    vec3 _e18 = r;
    r = (idx == 2.0) ? s2_ : _e18;
    vec3 _e22 = r;
    r = (idx == 3.0) ? s3_ : _e22;
    vec3 _e26 = r;
    r = (idx == 4.0) ? s4_ : _e26;
    vec3 _e30 = r;
    r = (idx == 5.0) ? s5_ : _e30;
    vec3 _e34 = r;
    r = (idx == 6.0) ? s6_ : _e34;
    vec3 _e38 = r;
    r = (idx == 7.0) ? s7_ : _e38;
    vec3 _e42 = r;
    r = (idx == 8.0) ? s8_ : _e42;
    vec3 _e46 = r;
    r = (idx == 9.0) ? s9_ : _e46;
    vec3 _e50 = r;
    r = (idx == 10.0) ? s10_ : _e50;
    vec3 _e54 = r;
    r = (idx == 11.0) ? s11_ : _e54;
    vec3 _e58 = r;
    return _e58;
}

vec3 mfRampCyc(
    float tIn,
    float n,
    vec3 s0_1,
    vec3 s1_1,
    vec3 s2_1,
    vec3 s3_1,
    vec3 s4_1,
    vec3 s5_1,
    vec3 s6_1,
    vec3 s7_1,
    vec3 s8_1,
    vec3 s9_1,
    vec3 s10_1,
    vec3 s11_1
) {
    float k_3 = clamp(floor(n + 0.5), 1.0, 12.0);
    float x = fract(tIn) * k_3;
    float i0_ = min(floor(x), k_3 - 1.0);
    float i1_ = ((i0_ + 1.0) >= k_3) ? 0.0 : i0_ + 1.0;
    vec3 _e33 = mfRampPick(i0_, s0_1, s1_1, s2_1, s3_1, s4_1, s5_1, s6_1, s7_1, s8_1, s9_1, s10_1, s11_1);
    vec3 _e34 = mfRampPick(i1_, s0_1, s1_1, s2_1, s3_1, s4_1, s5_1, s6_1, s7_1, s8_1, s9_1, s10_1, s11_1);
    return mix(_e33, _e34, x - i0_);
}

vec3 mfRampLin(
    float tIn_1,
    float n_1,
    vec3 s0_2,
    vec3 s1_2,
    vec3 s2_2,
    vec3 s3_2,
    vec3 s4_2,
    vec3 s5_2,
    vec3 s6_2,
    vec3 s7_2,
    vec3 s8_2,
    vec3 s9_2,
    vec3 s10_2,
    vec3 s11_2
) {
    float k_4 = clamp(floor(n_1 + 0.5), 1.0, 12.0);
    float x_1 = clamp(tIn_1, 0.0, 1.0) * (k_4 - 1.0);
    float i0_1 = clamp(floor(x_1), 0.0, max(k_4 - 2.0, 0.0));
    vec3 _e33 = mfRampPick(i0_1, s0_2, s1_2, s2_2, s3_2, s4_2, s5_2, s6_2, s7_2, s8_2, s9_2, s10_2, s11_2);
    vec3 _e36 = mfRampPick(i0_1 + 1.0, s0_2, s1_2, s2_2, s3_2, s4_2, s5_2, s6_2, s7_2, s8_2, s9_2, s10_2, s11_2);
    return mix(_e33, _e36, x_1 - i0_1);
}

MfRamp mfRampOf(
    float n_2,
    vec3 s0_3,
    vec3 s1_3,
    vec3 s2_3,
    vec3 s3_3,
    vec3 s4_3,
    vec3 s5_3,
    vec3 s6_3,
    vec3 s7_3,
    vec3 s8_3,
    vec3 s9_3,
    vec3 s10_3,
    vec3 s11_3
) {
    return MfRamp(n_2, s0_3, s1_3, s2_3, s3_3, s4_3, s5_3, s6_3, s7_3, s8_3, s9_3, s10_3, s11_3);
}

vec3 mfRampCycR(
    float t,
    MfRamp r_1
) {
    vec3 _e15 = mfRampCyc(t, r_1.n, r_1.s0_, r_1.s1_, r_1.s2_, r_1.s3_, r_1.s4_, r_1.s5_, r_1.s6_, r_1.s7_, r_1.s8_, r_1.s9_, r_1.s10_, r_1.s11_);
    return _e15;
}

vec3 mfRampLinR(
    float t_1,
    MfRamp r_2
) {
    vec3 _e15 = mfRampLin(t_1, r_2.n, r_2.s0_, r_2.s1_, r_2.s2_, r_2.s3_, r_2.s4_, r_2.s5_, r_2.s6_, r_2.s7_, r_2.s8_, r_2.s9_, r_2.s10_, r_2.s11_);
    return _e15;
}

float lqHash(
    vec2 pIn
) {
    vec2 p_1 = vec2(0);
    p_1 = fract(pIn * vec2(123.34, 456.21));
    vec2 _e7 = p_1;
    vec2 _e8 = p_1;
    vec2 _e9 = p_1;
    p_1 = _e7 + vec2(dot(_e8, _e9 + vec2(45.32)));
    float _e17 = p_1.x;
    float _e19 = p_1.y;
    return fract(_e17 * _e19);
}

float lqNoise(
    vec2 p_2
) {
    vec2 f = vec2(0);
    vec2 i_4 = floor(p_2);
    f = fract(p_2);
    vec2 _e4 = f;
    vec2 _e5 = f;
    vec2 _e7 = f;
    f = (_e4 * _e5) * (vec2(3.0) - (2.0 * _e7));
    float _e14 = lqHash(i_4);
    float _e19 = lqHash(i_4 + vec2(1.0, 0.0));
    float _e21 = f.x;
    float _e27 = lqHash(i_4 + vec2(0.0, 1.0));
    float _e32 = lqHash(i_4 + vec2(1.0, 1.0));
    float _e34 = f.x;
    float _e37 = f.y;
    return mix(mix(_e14, _e19, _e21), mix(_e27, _e32, _e34), _e37);
}

vec2 lqFbm(
    vec2 pIn_1,
    float bs
) {
    vec2 p_3 = vec2(0);
    float s = 0.0;
    float a = 0.5;
    float m = 0.0;
    float vr = 0.0;
    float g = 1.0;
    int i_1 = 0;
    p_3 = pIn_1;
    float e = (-6.0 * bs) * bs;
    uvec2 loop_bound = uvec2(4294967295u);
    bool loop_init = true;
    while(true) {
        if (all(equal(loop_bound, uvec2(0u)))) { break; }
        loop_bound -= uvec2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
            int _e74 = i_1;
            i_1 = int(uint(_e74) + uint(1));
        }
        loop_init = false;
        int _e18 = i_1;
        if (_e18 < 5) {
        } else {
            break;
        }
        {
            float _e21 = g;
            float b_1 = exp(e * _e21);
            float _e24 = s;
            float _e25 = a;
            vec2 _e26 = p_3;
            float _e27 = lqNoise(_e26);
            s = _e24 + (_e25 * (0.5 + (b_1 * (_e27 - 0.5))));
            float _e35 = vr;
            float _e36 = a;
            float _e37 = a;
            vr = _e35 + ((_e36 * _e37) * (1.0 - (b_1 * b_1)));
            float _e44 = m;
            float _e45 = a;
            m = _e44 + _e45;
            float _e47 = a;
            a = _e47 * 0.5;
            float _e50 = g;
            g = _e50 * GL_KG;
            float _e54 = p_3.x;
            float _e58 = p_3.y;
            float _e63 = p_3.x;
            float _e67 = p_3.y;
            p_3 = vec2((0.8 * _e54) - (0.6 * _e58), (0.6 * _e63) + (0.8 * _e67)) * 2.03;
        }
    }
    float _e77 = s;
    float _e78 = m;
    float _e81 = vr;
    float _e84 = m;
    return vec2(_e77 / _e78, (GL_KR * sqrt(_e81)) / _e84);
}

float lqRidge(
    float v,
    float k
) {
    return pow(clamp(1.0 - abs((v * 2.0) - 1.0), 0.0, 1.0), k);
}

vec3 lqRamp(
    float v_1,
    vec3 cA,
    vec3 cB,
    vec3 cC,
    vec3 cD,
    Uniforms u
) {
    vec3 c = vec3(0);
    c = mix(cA, cB, smoothstep(0.0, 0.45, v_1));
    vec3 _e10 = c;
    c = mix(_e10, cC, smoothstep(0.38, 0.72, v_1));
    vec3 _e15 = c;
    c = mix(_e15, cD, smoothstep(0.68, 1.0, v_1));
    vec3 _e20 = c;
    float _e23 = u.paletteCount;
    vec4 _e26 = u.paletteStop0_;
    vec4 _e30 = u.paletteStop1_;
    vec4 _e34 = u.paletteStop2_;
    vec4 _e38 = u.paletteStop3_;
    vec4 _e42 = u.paletteStop4_;
    vec4 _e46 = u.paletteStop5_;
    vec4 _e50 = u.paletteStop6_;
    vec4 _e54 = u.paletteStop7_;
    vec4 _e58 = u.paletteStop8_;
    vec4 _e62 = u.paletteStop9_;
    vec4 _e66 = u.paletteStop10_;
    vec4 _e70 = u.paletteStop11_;
    vec3 _e72 = mfRampLin(v_1, _e23, _e26.xyz, _e30.xyz, _e34.xyz, _e38.xyz, _e42.xyz, _e46.xyz, _e50.xyz, _e54.xyz, _e58.xyz, _e62.xyz, _e66.xyz, _e70.xyz);
    float _e75 = u.paletteCount;
    return (_e75 > 0.5) ? _e72 : _e20;
}

float lqRidgeS(
    vec2 vs,
    float k_1
) {
    float d_1 = GL_GH * vs.y;
    float _e7 = lqRidge(vs.x - d_1, k_1);
    float _e9 = lqRidge(vs.x, k_1);
    float _e15 = lqRidge(vs.x + d_1, k_1);
    return ((_e7 + (4.0 * _e9)) + _e15) / 6.0;
}

float lqStepS(
    vec2 vs_1,
    float a_1,
    float b
) {
    float d_2 = GL_GH * vs_1.y;
    return ((smoothstep(a_1, b, vs_1.x - d_2) + (4.0 * smoothstep(a_1, b, vs_1.x))) + smoothstep(a_1, b, vs_1.x + d_2)) / 6.0;
}

float lqPowS(
    vec2 vs_2,
    float k_2
) {
    float d_3 = GL_GH * vs_2.y;
    return ((pow(clamp(vs_2.x - d_3, 0.0, 1.0), k_2) + (4.0 * pow(clamp(vs_2.x, 0.0, 1.0), k_2))) + pow(clamp(vs_2.x + d_3, 0.0, 1.0), k_2)) / 6.0;
}

vec3 glsFinishPresetFluid(
    vec3 colorIn,
    vec2 p_4,
    Uniforms u
) {
    vec3 color = vec3(0);
    color = colorIn;
    vec3 _e3 = color;
    vec4 _e6 = u.highlightColor;
    float _e10 = u.shade;
    color = mix(_e3, _e6.xyz, (_e10 * 0.22) * smoothstep(0.15, 1.15, dot(p_4, vec2(-0.32, 0.78))));
    vec3 _e22 = color;
    float _e25 = u.shade;
    color = _e22 * (1.0 - ((_e25 * 0.34) * smoothstep(-0.1, 1.2, dot(p_4, vec2(0.45, -0.62)))));
    vec3 _e39 = color;
    float _e42 = u.shade;
    color = _e39 * (1.0 - ((_e42 * 0.22) * smoothstep(0.72, 1.08, length(p_4))));
    vec3 _e53 = color;
    return clamp(_e53, vec3(0.0), vec3(1.0));
}

vec3 glsFinishEmissionFluid(
    vec3 colorIn,
    vec2 p,
    Uniforms u
) {
    vec3 color = colorIn;
    if (u.glassEnabled > 0.5) {
        color = mix(
            color,
            u.highlightColor.xyz,
            u.shade * 0.22
                * smoothstep(0.15, 1.15, dot(p, vec2(-0.32, 0.78)))
        );
    }
    color *= 1.0 - u.shade * 0.34
        * smoothstep(-0.1, 1.2, dot(p, vec2(0.45, -0.62)));
    color *= 1.0 - u.shade * 0.22
        * smoothstep(0.72, 1.08, length(p));
    return clamp(color, vec3(0.0), vec3(1.0));
}

vec2 glsSiriBand(
    vec2 q,
    float drift,
    float phaseOffset,
    float amplitude,
    float mainY,
    float envelope,
    float softness
) {
    float y = (amplitude * envelope) * sin(((q.x * 1.0) + drift) + phaseOffset);
    float distanceToLine = abs(q.y - y);
    float line = 0.018 / (sqrt((distanceToLine * distanceToLine) + (softness * softness)) + 0.026);
    float bandDistance = max(0.0, max(q.y - max(mainY, y), min(mainY, y) - q.y));
    float band = 0.018 / (bandDistance + 0.075);
    return vec2(line, band);
}

vec3 glsSiriFluid(
    vec2 p_5,
    float t_2,
    Uniforms u
) {
    vec3 color_1 = vec3(0);
    float _e4 = u.zoom;
    float scale_1 = 0.74 + (_e4 * 0.34);
    vec2 q_5 = p_5 / vec2(scale_1);
    float xNorm = q_5.x;
    float envelopeBase = cos(1.5707964 * min(abs(0.9 * xNorm), 1.0));
    float envelope_1 = envelopeBase * envelopeBase;
    float low = 0.5 + (0.5 * cos(t_2 * 0.37));
    float mid = 0.5 + (0.5 * sin((t_2 * 0.51) + 1.2));
    float high = 0.5 + (0.5 * cos((t_2 * 0.73) + 2.1));
    float drift_1 = t_2 * 2.4;
    float _e50 = u.ridgeAmt;
    float mainAmplitude = (0.25 + (_e50 * 0.075)) + (low * 0.018);
    float bandAmplitude = (mainAmplitude + (mid * 0.025)) + (high * 0.018);
    float mainY_1 = (mainAmplitude * envelope_1) * sin((q_5.x * 1.1) + drift_1);
    float _e73 = u.warp;
    float separation = (1.85 + (_e73 * 0.2)) + (mid * 0.28);
    float _e83 = u.ridgeAmt;
    float softness_2 = (0.035 + ((1.0 - _e83) * 0.018)) + (mid * 0.006);
    vec2 _e94 = glsSiriBand(q_5, drift_1, -(separation), bandAmplitude, mainY_1, envelope_1, softness_2);
    vec2 _e98 = glsSiriBand(q_5, drift_1, -(separation) * 0.34, bandAmplitude, mainY_1, envelope_1, softness_2);
    vec2 _e101 = glsSiriBand(q_5, drift_1, separation * 0.34, bandAmplitude, mainY_1, envelope_1, softness_2);
    vec2 _e102 = glsSiriBand(q_5, drift_1, separation, bandAmplitude, mainY_1, envelope_1, softness_2);
    float w0_ = _e94.x + _e94.y;
    float w1_ = _e98.x + _e98.y;
    float w2_ = _e101.x + _e101.y;
    float w3_ = _e102.x + _e102.y;
    float total = ((w0_ + w1_) + w2_) + w3_;
    float dominant0_ = w0_ * w0_;
    float dominant1_ = w1_ * w1_;
    float dominant2_ = w2_ * w2_;
    float dominant3_ = w3_ * w3_;
    float dominantTotal = ((dominant0_ + dominant1_) + dominant2_) + dominant3_;
    vec4 _e127 = u.colorA;
    vec4 _e132 = u.colorC;
    vec4 _e138 = u.colorB;
    vec4 _e144 = u.colorD;
    vec3 spectral = ((((_e127.xyz * dominant0_) + (_e132.xyz * dominant1_)) + (_e138.xyz * dominant2_)) + (_e144.xyz * dominant3_)) / vec3(max(dominantTotal, 0.0001));
    float energy = (1.0 - exp(-(total) * 0.58)) * envelope_1;
    float mainDistance = abs(q_5.y - mainY_1);
    float whiteCore = exp((-(mainDistance) * mainDistance) / 0.0028) * envelope_1;
    vec4 _e170 = u.colorD;
    vec4 _e174 = u.colorB;
    float glassFill = u.glassEnabled > 0.5 ? 1.0 : 0.0;
    vec3 atmosphere = mix(
        _e170.xyz, _e174.xyz, smoothstep(-0.7, 0.7, q_5.y)) * 0.018 * glassFill;
    color_1 = atmosphere + ((spectral * energy) * 1.14);
    vec3 _e188 = color_1;
    vec4 _e191 = u.highlightColor;
    color_1 = _e188 + ((_e191.xyz * whiteCore) * (0.18 + (0.1 * low)));
    float emissionMask = mix(
        smoothstep(0.08, 0.25, energy + whiteCore * 0.12),
        1.0,
        glassFill
    );
    color_1 *= emissionMask;
    vec3 _e200 = color_1;
    vec3 _e203 = color_1;
    color_1 = _e200 / (vec3(1.0) + (_e203 * 0.18));
    vec3 _e208 = color_1;
    vec3 _e209 = glsFinishEmissionFluid(_e208, p_5, u);
    return _e209;
}

float glsSpectrumHeight(
    vec2 q_1,
    float t_3,
    float frequency,
    float phaseOffset_1,
    float amplitude_1
) {
    float x_2 = q_1.x * 2.15;
    float envelope_2 = pow(4.0 / (4.0 + (x_2 * x_2)), 4.0);
    float breathing = 0.82 + (0.18 * sin((t_3 * 0.48) + (phaseOffset_1 * 0.7)));
    float wave = abs(sin(((frequency * x_2) - (t_3 * 1.36)) + phaseOffset_1));
    return ((envelope_2 * amplitude_1) * breathing) * (0.28 + (0.72 * wave));
}

float glsSpectrumLayer(
    vec2 q_2,
    float height,
    float softness_1
) {
    return (1.0 - smoothstep(max(height - softness_1, 0.0), height + softness_1, abs(q_2.y))) * smoothstep(0.0, 0.045, height);
}

vec3 glsSpectrumFluid(
    vec2 p_6,
    float t_4,
    Uniforms u
) {
    vec3 color_2 = vec3(0);
    float _e4 = u.zoom;
    float scale_2 = 0.74 + (_e4 * 0.34);
    vec2 q_6 = p_6 / vec2(scale_2);
    float _e13 = u.ridgeAmt;
    float amplitude_2 = 0.26 + (_e13 * 0.27);
    float _e20 = u.warp;
    float frequency_1 = 0.72 + (_e20 * 0.095);
    float _e27 = u.ridgeAmt;
    float softness_3 = 0.026 + ((1.0 - _e27) * 0.032);
    float _e39 = glsSpectrumHeight(q_6, t_4, frequency_1 * 0.82, -1.2, amplitude_2 * 0.72);
    float _e41 = glsSpectrumHeight(q_6, t_4, frequency_1, 0.45, amplitude_2);
    float _e47 = glsSpectrumHeight(q_6, t_4, frequency_1 * 1.17, 2.05, amplitude_2 * 0.82);
    float _e48 = glsSpectrumLayer(q_6, _e39, softness_3);
    float _e49 = glsSpectrumLayer(q_6, _e41, softness_3);
    float _e50 = glsSpectrumLayer(q_6, _e47, softness_3);
    float spectrumX = q_6.x * 2.15;
    float envelope_3 = pow(4.0 / (4.0 + (spectrumX * spectrumX)), 4.0);
    float support = exp((-(q_6.y) * q_6.y) / 0.00072) * envelope_3;
    float total_1 = (_e48 + _e49) + _e50;
    vec4 _e73 = u.colorB;
    vec4 _e78 = u.colorC;
    vec4 _e84 = u.colorD;
    vec3 spectral_1 = (((_e73.xyz * _e48) + (_e78.xyz * _e49)) + (_e84.xyz * _e50)) / vec3(max(total_1, 0.001));
    vec4 _e94 = u.colorD;
    float glassFill = u.glassEnabled > 0.5 ? 1.0 : 0.0;
    color_2 = (_e94.xyz * 0.025 * glassFill)
            + (spectral_1 * (1.0 - exp(-(total_1) * 0.86)));
    vec3 _e107 = color_2;
    vec4 _e110 = u.colorA;
    color_2 = _e107 + ((_e110.xyz * support) * 0.58);
    vec3 _e116 = color_2;
    vec3 _e119 = color_2;
    color_2 = _e116 / (vec3(1.0) + (_e119 * 0.2));
    vec3 _e124 = color_2;
    vec3 _e125 = glsFinishEmissionFluid(_e124, p_6, u);
    return _e125;
}

float glsAuroraLayer(
    vec2 p_7,
    float t_5,
    float offset,
    Uniforms u
) {
    float drift_2 = (t_5 * 0.18) + (offset * 2.5);
    float _e11 = u.warp;
    float wave1_ = sin(((p_7.x * (2.0 + (_e11 * 0.13))) + drift_2) + (offset * 6.0)) * 0.25;
    float wave2_ = sin(((p_7.x * 3.7) + (drift_2 * 1.3)) + (offset * 4.0)) * 0.12;
    float wave3_ = sin(((p_7.x * 7.2) + (drift_2 * 0.7)) + (offset * 8.0)) * 0.055;
    vec2 _e62 = lqFbm(vec2((p_7.x * 1.6) + (drift_2 * 0.35), (p_7.y * 0.8) + (offset * 3.0)), 0.018);
    float noiseValue = _e62.x;
    float center = ((((offset * 0.46) + wave1_) + wave2_) + wave3_) + ((noiseValue - 0.5) * 0.28);
    float dist = abs(p_7.y - center);
    float _e81 = u.ridgeAmt;
    float glow_1 = exp((-(dist) * dist) * (13.0 - (5.0 * _e81)));
    vec2 _e102 = lqFbm(vec2((p_7.x * 4.0) + (t_5 * 0.22), (p_7.y * 7.0) + (offset * 5.0)), 0.012);
    float shimmer = _e102.x;
    return glow_1 * (0.64 + (0.36 * shimmer));
}

vec3 glsAuroraFluid(
    vec2 p_8,
    float t_6,
    Uniforms u
) {
    vec3 color_3 = vec3(0);
    float _e4 = u.zoom;
    vec2 q_7 = p_8 * (0.82 + (_e4 * 0.58));
    float _e11 = glsAuroraLayer(q_7, t_6, -0.72, u);
    float _e13 = glsAuroraLayer(q_7, t_6, 0.0, u);
    float _e15 = glsAuroraLayer(q_7, t_6, 0.72, u);
    vec4 _e18 = u.colorA;
    color_3 = _e18.xyz * (0.46 + (0.18 * (q_7.y + 1.0)));
    vec3 _e29 = color_3;
    vec4 _e32 = u.colorB;
    color_3 = _e29 + ((_e32.xyz * _e11) * 1.3);
    vec3 _e38 = color_3;
    vec4 _e41 = u.colorC;
    color_3 = _e38 + ((_e41.xyz * _e13) * 1.15);
    vec3 _e47 = color_3;
    vec4 _e50 = u.colorD;
    color_3 = _e47 + ((_e50.xyz * _e15) * 1.2);
    vec3 _e56 = color_3;
    vec4 _e59 = u.colorB;
    vec4 _e63 = u.colorD;
    color_3 = _e56 + ((mix(_e59.xyz, _e63.xyz, 0.5) * min(_e11 * _e15, _e13)) * 0.65);
    vec2 starUv = (q_7 + vec2(1.0)) * 18.0;
    vec2 starCell = floor(starUv);
    float _e79 = lqHash(starCell);
    float starPoint = exp(-(dot(fract(starUv) - vec2(0.5), fract(starUv) - vec2(0.5))) * 90.0);
    float stars = (step(0.965, _e79) * starPoint) * (0.55 + (0.45 * sin((t_6 * (1.0 + (_e79 * 2.0))) + (_e79 * 6.28))));
    vec3 _e110 = color_3;
    vec4 _e113 = u.highlightColor;
    color_3 = _e110 + ((_e113.xyz * stars) * (1.0 - clamp((_e11 + _e13) + _e15, 0.0, 1.0)));
    vec3 _e125 = color_3;
    vec3 _e128 = color_3;
    color_3 = _e125 / (vec3(1.0) + (_e128 * 0.28));
    vec3 _e133 = color_3;
    vec3 _e134 = glsFinishPresetFluid(_e133, p_8, u);
    return _e134;
}

vec2 glsRotate(
    vec2 p_9,
    float angle
) {
    float c_1 = cos(angle);
    float s_1 = sin(angle);
    return vec2((c_1 * p_9.x) - (s_1 * p_9.y), (s_1 * p_9.x) + (c_1 * p_9.y));
}

float glsNeuroShape(
    vec2 pIn_2,
    float t_7,
    Uniforms u
) {
    vec2 p_10 = vec2(0);
    vec2 sineAccum = vec2(0.0);
    vec2 result = vec2(0.0);
    float scale = 8.0;
    int j = 0;
    float _e4 = u.zoom;
    p_10 = pIn_2 * (0.34 + (0.08 * _e4));
    uvec2 loop_bound_1 = uvec2(4294967295u);
    bool loop_init_1 = true;
    while(true) {
        if (all(equal(loop_bound_1, uvec2(0u)))) { break; }
        loop_bound_1 -= uvec2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
            int _e60 = j;
            j = int(uint(_e60) + uint(1));
        }
        loop_init_1 = false;
        int _e21 = j;
        if (_e21 < 11) {
        } else {
            break;
        }
        {
            vec2 _e24 = p_10;
            vec2 _e26 = glsRotate(_e24, 1.0);
            p_10 = _e26;
            vec2 _e27 = sineAccum;
            vec2 _e29 = glsRotate(_e27, 1.0);
            sineAccum = _e29;
            vec2 _e30 = p_10;
            float _e31 = scale;
            int _e33 = j;
            vec2 _e37 = sineAccum;
            vec2 layer = (((_e30 * _e31) + vec2(float(_e33))) + _e37) - vec2(t_7 * 0.34);
            vec2 _e43 = sineAccum;
            sineAccum = _e43 + sin(layer);
            vec2 _e46 = result;
            float _e53 = scale;
            result = _e46 + ((vec2(0.5) + (0.5 * cos(layer))) / vec2(_e53));
            float _e57 = scale;
            scale = _e57 * 1.16;
        }
    }
    float _e64 = result.x;
    float _e66 = result.y;
    return _e64 + _e66;
}

vec3 glsPlasmaFluid(
    vec2 p_11,
    float t_8,
    Uniforms u
) {
    vec3 color_4 = vec3(0);
    float _e2 = glsNeuroShape(p_11, t_8, u);
    float _e5 = u.warp;
    float phase = (((_e2 * (10.0 + _e5)) + (p_11.x * 1.7)) - (p_11.y * 1.3)) - (t_8 * 0.52);
    float _e22 = u.ridgeAmt;
    float ridgeWidth = 0.62 - (0.24 * _e22);
    float _e32 = u.sharp;
    float primary = pow(abs(cos(phase)), max(1.3, _e32 * ridgeWidth));
    float _e52 = u.sharp;
    float secondary = pow(abs(cos(((phase * 0.53) + (atan(p_11.y, p_11.x) * 2.0)) + (t_8 * 0.21))), max(1.6, _e52 * (ridgeWidth + 0.1)));
    float filaments = max(primary, secondary * 0.64);
    float core = pow(primary, 4.0);
    float polarity = 0.5 + (0.5 * sin((phase * 0.37) + (_e2 * 3.0)));
    vec4 _e75 = u.colorA;
    vec4 _e81 = u.colorD;
    color_4 = mix(_e75.xyz * 0.42, _e81.xyz * 0.48, polarity * 0.46);
    vec3 _e89 = color_4;
    vec4 _e92 = u.colorB;
    color_4 = mix(_e89, _e92.xyz, filaments * 0.72);
    vec3 _e97 = color_4;
    vec4 _e100 = u.colorC;
    color_4 = mix(_e97, _e100.xyz, core * 0.68);
    vec3 _e105 = color_4;
    vec4 _e108 = u.highlightColor;
    color_4 = _e105 + ((_e108.xyz * pow(core, 3.0)) * 0.16);
    vec3 _e116 = color_4;
    vec3 _e119 = color_4;
    color_4 = _e116 / (vec3(1.0) + (_e119 * 0.34));
    vec3 _e124 = color_4;
    vec3 _e125 = glsFinishPresetFluid(_e124, p_11, u);
    return _e125;
}

vec3 glsChromeFluid(
    vec2 p_12,
    float t_9,
    Uniforms u
) {
    vec2 q_3 = vec2(0);
    int i_2 = 1;
    vec3 color_5 = vec3(0);
    float _e4 = u.zoom;
    q_3 = p_12 * (1.0 + (_e4 * 0.35));
    float _e13 = u.warp;
    float amplitude_3 = 0.028 * _e13;
    uvec2 loop_bound_2 = uvec2(4294967295u);
    bool loop_init_2 = true;
    while(true) {
        if (all(equal(loop_bound_2, uvec2(0u)))) { break; }
        loop_bound_2 -= uvec2(loop_bound_2.y == 0u, 1u);
        if (!loop_init_2) {
            int _e53 = i_2;
            i_2 = int(uint(_e53) + uint(1));
        }
        loop_init_2 = false;
        int _e18 = i_2;
        if (_e18 <= 9) {
        } else {
            break;
        }
        {
            int _e21 = i_2;
            float fi = float(_e21);
            float _e25 = q_3.x;
            float _e30 = q_3.y;
            q_3.x = _e25 + ((amplitude_3 / fi) * cos(((fi * 2.7) * _e30) + (t_9 * 0.46)));
            float _e40 = q_3.y;
            float _e45 = q_3.x;
            q_3.y = _e40 + ((amplitude_3 / fi) * cos(((fi * 3.1) * _e45) - (t_9 * 0.4)));
        }
    }
    float _e59 = q_3.y;
    float _e62 = q_3.x;
    float denominator = max(abs(sin(((t_9 * 0.24) - _e59) - _e62)), 0.045);
    float flare = clamp(1.0 / denominator, 0.0, 18.0);
    float metal_ = smoothstep(1.15, 7.5, flare);
    float _e77 = q_3.x;
    float _e79 = q_3.y;
    float _e83 = u.sharp;
    float fold = 0.5 + (0.5 * cos(((_e77 - _e79) * (3.2 + (_e83 * 0.28))) + (t_9 * 0.32)));
    float value = clamp((metal_ * 0.74) + (fold * 0.36), 0.0, 1.0);
    vec4 _e107 = u.colorD;
    vec4 _e111 = u.colorC;
    vec4 _e115 = u.colorB;
    vec4 _e119 = u.colorA;
    vec3 _e121 = lqRamp(value, _e107.xyz, _e111.xyz, _e115.xyz, _e119.xyz, u);
    color_5 = _e121;
    vec3 _e123 = color_5;
    vec4 _e126 = u.colorA;
    color_5 = mix(_e123, _e126.xyz, pow(metal_, 5.0) * 0.62);
    vec3 _e133 = color_5;
    vec3 _e134 = glsFinishPresetFluid(_e133, p_12, u);
    return _e134;
}

float glsChromaticMetalPhase(
    vec2 p,
    float t,
    Uniforms u
) {
    float angle = u.metalAngle * 0.01745329252;
    float scale = max(u.metalScale, 0.05);
    float stretch = mix(0.48, 1.58, clamp(u.metalStretch, 0.0, 1.0));
    vec2 q = glsRotate(p / scale, angle);
    q = vec2(q.x / stretch, q.y * stretch);
    float cycle = t * 0.46 + u.metalPhase * 6.28318530718;
    float evolution = clamp(u.metalEvolution, 0.0, 2.0);
    q.x += sin(q.y * 1.86 - cycle) * 0.095 * evolution;
    q.x += sin((q.x + q.y) * 1.28 + cycle * 2.0 + 1.4) * 0.045 * evolution;
    q.y += sin(q.x * 1.52 + cycle + 0.8) * 0.07 * evolution;
    float repeats = max(u.bandDensity, 1.0);
    return q.x * repeats * 2.18
         + sin(q.y * (1.3 + repeats * 0.26) - cycle) * 0.56 * evolution
         + sin((q.x - q.y) * 1.34 + cycle * 2.0 + 1.7) * 0.27 * evolution
         + sin((q.x * 0.72 + q.y) * 2.1 - cycle * 3.0 + 0.35) * 0.11 * evolution
         + sin(cycle) * 0.1
         + sin(cycle * 3.0 + 0.7) * 0.035
         + cycle
         + u.metalOffset * 6.28318530718;
}

float glsChromaticMetalTone(
    float phase,
    Uniforms u
) {
    float wave = 0.5 + 0.5 * cos(phase);
    float roughness = clamp(u.metalRoughness, 0.0, 1.0);
    float depth = clamp(u.metalDepth, 0.0, 1.0);
    float edge = 0.025 + roughness * 0.18;
    float broadReflection = smoothstep(0.5 - edge, 0.5 + edge, wave);
    float hardReflection = pow(wave, mix(13.0, 4.0, roughness));
    float blackFold = pow(1.0 - wave, mix(9.0, 3.0, roughness));
    float body = mix(wave, broadReflection, 0.2 + depth * 0.3);
    return clamp(0.018 + body * (0.46 + depth * 0.12)
                        + hardReflection * (0.3 + depth * 0.42)
                        - blackFold * (0.07 + depth * 0.11), 0.0, 1.0);
}

vec3 glsChromaticMetalSample(
    vec2 p,
    float t,
    Uniforms u
) {
    float phase = glsChromaticMetalPhase(p, t, u);
    float angle = u.metalAngle * 0.01745329252;
    vec2 brushP = glsRotate(p / max(u.metalScale, 0.05), angle);
    float brushed = sin(brushP.y * 146.0
                               + sin(brushP.x * 11.0) * 0.58)
                  + 0.48 * sin(brushP.y * 317.0 - brushP.x * 5.0);
    float brushAmount = 0.004 + clamp(u.metalRoughness, 0.0, 1.0) * 0.014;
    float tone = clamp(glsChromaticMetalTone(phase, u)
                              + brushed * brushAmount, 0.0, 1.0);
    return lqRamp(tone, u.colorD.xyz, u.colorB.xyz, u.colorC.xyz, u.colorA.xyz, u);
}

vec3 glsChromaticMetalFluid(
    vec2 p,
    float t,
    Uniforms u
) {
    float angle = u.metalAngle * 0.01745329252;
    vec2 splitDirection = glsRotate(vec2(0.0, 1.0), angle);
    vec2 split = splitDirection * u.chromaticShift * 0.045;
    vec3 redSample = glsChromaticMetalSample(p + split, t, u);
    vec3 neutral = glsChromaticMetalSample(p, t, u);
    vec3 blueSample = glsChromaticMetalSample(p - split, t, u);
    vec3 optical = vec3(redSample.x, neutral.y, blueSample.z);
    float fringe = clamp(length(optical - neutral) * 4.0, 0.0, 1.0);
    vec3 color = mix(neutral, optical,
        clamp(u.chromaticShift * (0.72 + fringe * 0.28), 0.0, 1.0));
    float centerTone = glsChromaticMetalTone(glsChromaticMetalPhase(p, t, u), u);
    float glint = pow(centerTone,
        mix(12.0, 5.0, clamp(u.metalRoughness, 0.0, 1.0)));
    color = mix(color, u.highlightColor.xyz,
        glint * clamp(u.metalDepth, 0.0, 1.0) * 0.06);
    float radial2 = clamp(dot(p, p), 0.0, 1.0);
    vec3 normal = normalize(vec3(
        p, sqrt(max(1.0 - radial2, 0.0))));
    float roughness = clamp(u.metalRoughness, 0.0, 1.0);
    float depth = clamp(u.metalDepth, 0.0, 1.0);
    float key = pow(max(dot(normal,
        normalize(vec3(-0.48, 0.62, 0.62))), 0.0),
        mix(7.0, 3.0, roughness));
    float fill = pow(max(dot(normal,
        normalize(vec3(0.7, -0.34, 0.63))), 0.0),
        mix(10.0, 4.0, roughness));
    float limb = 1.0 - normal.z;
    float fresnel = pow(limb, 3.0);
    float rim = pow(limb, 10.0);
    color *= 0.86 + normal.z * 0.14;
    color = mix(color, u.highlightColor.xyz, key * (0.05 + depth * 0.13));
    color = mix(color, u.colorC.xyz, fill * (0.025 + depth * 0.07));
    color = mix(color, u.colorD.xyz, fresnel * (0.12 + depth * 0.15));
    color = mix(color, u.highlightColor.xyz, rim * (0.035 + depth * 0.055));
    return glsFinishPresetFluid(color, p, u);
}

vec3 glsOpalFluid(
    vec2 p_13,
    float t_10,
    Uniforms u
) {
    float d = float(0);
    float a_2 = 0.0;
    int i_3 = 0;
    vec3 color_6 = vec3(0);
    float _e4 = u.zoom;
    vec2 q_8 = p_13 * (0.8 + (_e4 * 0.64));
    float _e12 = u.warp;
    float complexity = 0.76 + (_e12 * 0.085);
    d = -(t_10) * 0.42;
    uvec2 loop_bound_3 = uvec2(4294967295u);
    bool loop_init_3 = true;
    while(true) {
        if (all(equal(loop_bound_3, uvec2(0u)))) { break; }
        loop_bound_3 -= uvec2(loop_bound_3.y == 0u, 1u);
        if (!loop_init_3) {
            int _e48 = i_3;
            i_3 = int(uint(_e48) + uint(1));
        }
        loop_init_3 = false;
        int _e25 = i_3;
        if (_e25 < 8) {
        } else {
            break;
        }
        {
            int _e28 = i_3;
            float fi_1 = float(_e28);
            float _e30 = a_2;
            float _e31 = d;
            float _e33 = a_2;
            a_2 = _e30 + cos((fi_1 - _e31) - ((_e33 * q_8.x) * complexity));
            float _e40 = d;
            float _e44 = a_2;
            d = _e40 + sin(((q_8.y * fi_1) * complexity) + _e44);
        }
    }
    float _e51 = d;
    d = _e51 + (t_10 * 0.42);
    float _e55 = d;
    float _e56 = a_2;
    vec2 c1_ = (cos(q_8 * vec2(_e55, _e56)) * 0.6) + vec2(0.4);
    float _e65 = a_2;
    float _e66 = d;
    float c2_ = (cos(_e65 + _e66) * 0.5) + 0.5;
    float _e76 = d;
    float _e77 = a_2;
    vec3 interference = vec3(0.5) + (0.5 * cos(((vec3(c1_.x, c1_.y, c2_) * cos(vec3(_e76, _e77, 2.5))) * 0.5) + vec3(0.5)));
    float tone = fract(((((interference.x * 0.37) + (interference.y * 0.51)) + (interference.z * 0.73)) + (c1_.x * 0.22)) - (c1_.y * 0.15));
    vec4 _e115 = u.colorB;
    vec4 _e119 = u.colorC;
    vec4 _e123 = u.colorD;
    vec4 _e127 = u.colorA;
    vec3 _e129 = lqRamp(tone, _e115.xyz, _e119.xyz, _e123.xyz, _e127.xyz, u);
    color_6 = _e129;
    vec3 _e131 = color_6;
    vec4 _e134 = u.colorA;
    color_6 = mix(_e131, _e134.xyz, 0.16 + (0.1 * interference.z));
    vec3 _e142 = color_6;
    vec3 _e145 = color_6;
    color_6 = _e142 / (vec3(1.0) + (_e145 * 0.16));
    vec3 _e150 = color_6;
    vec3 _e151 = glsFinishPresetFluid(_e150, p_13, u);
    return _e151;
}

vec3 glsFrostFluid(
    vec2 p_14,
    float t_11,
    Uniforms u
) {
    vec2 q_4 = vec2(0);
    vec3 color_7 = vec3(0);
    float _e4 = u.zoom;
    q_4 = p_14 * (0.66 + (_e4 * 0.92));
    float _e13 = q_4.y;
    q_4.y = _e13 + (t_11 * 0.055);
    float _e19 = u.zoom;
    float blur = 0.011 + (0.006 * _e19);
    vec2 _e24 = q_4;
    vec2 _e32 = lqFbm((_e24 * 1.14) + vec2(t_11 * 0.055, 0.0), blur);
    vec2 _e34 = q_4;
    vec2 _e43 = lqFbm((_e34 * 1.14) + vec2(6.8, -(t_11) * 0.048), blur);
    vec2 warpField = vec2(_e32.x, _e43.x);
    vec2 _e46 = q_4;
    float _e52 = u.warp;
    vec2 warped = _e46 + ((warpField - vec2(0.5)) * (0.28 + (_e52 * 0.17)));
    vec2 _e70 = lqFbm((warped * 1.48) + vec2(t_11 * 0.032, -(t_11) * 0.02), blur * 1.48);
    vec2 _e81 = lqFbm((warped * 2.36) + vec2(3.1, -(t_11) * 0.024), blur * 2.36);
    float _e84 = u.sharp;
    float _e85 = lqRidgeS(_e81, _e84);
    float _e88 = lqStepS(_e70, 0.1, 0.9);
    float _e100 = u.ridgeAmt;
    float value_1 = mix(_e88, clamp((_e85 * 0.8) + (_e70.x * 0.46), 0.0, 1.0), _e100);
    vec4 _e104 = u.colorA;
    vec4 _e108 = u.colorB;
    vec4 _e112 = u.colorC;
    vec4 _e116 = u.colorD;
    vec3 _e118 = lqRamp(value_1, _e104.xyz, _e108.xyz, _e112.xyz, _e116.xyz, u);
    color_7 = _e118;
    vec3 _e120 = color_7;
    vec4 _e123 = u.colorA;
    color_7 = mix(_e120, _e123.xyz, 0.08 * smoothstep(0.62, 0.92, _e70.x));
    vec3 _e132 = color_7;
    vec3 _e133 = glsFinishPresetFluid(_e132, p_14, u);
    return _e133;
}

vec3 glsVoiceWaveFluid(
    vec2 p_15,
    float t_12,
    Uniforms u
) {
    vec3 color_8 = vec3(0);
    float _e4 = u.zoom;
    float scale_3 = 0.76 + (_e4 * 0.34);
    vec2 q_9 = p_15 / vec2(scale_3);
    float rimEnvelope = pow(max(1.0 - (q_9.x * q_9.x), 0.0), 0.72);
    float drift_3 = t_12 * 0.82;
    float _e24 = u.warp;
    float amplitude_4 = 0.2 + (_e24 * 0.018);
    float mainY_2 = rimEnvelope * ((amplitude_4 * sin((q_9.x * 1.48) + drift_3)) + (0.055 * sin(((q_9.x * 3.2) - (drift_3 * 0.43)) + 1.1)));
    float distance = q_9.y - mainY_2;
    float _e52 = u.ridgeAmt;
    float width = 0.11 + ((1.0 - _e52) * 0.075);
    float membrane = exp((-(distance) * distance) / max(width * width, 0.001)) * rimEnvelope;
    float upperVeil = exp((-(distance - 0.105) * (distance - 0.105)) / max((width * width) * 2.4, 0.001)) * rimEnvelope;
    float lowerVeil = exp((-(distance + 0.115) * (distance + 0.115)) / max((width * width) * 2.8, 0.001)) * rimEnvelope;
    float crest = exp((-(distance) * distance) / 0.0026) * rimEnvelope;
    float depth = sqrt(max(1.0 - clamp(dot(p_15, p_15), 0.0, 1.0), 0.0));
    vec4 _e112 = u.colorA;
    vec4 _e118 = u.colorD;
    color_8 = mix(_e112.xyz * 0.7, _e118.xyz * 0.34, smoothstep(-0.82, 0.82, q_9.y));
    vec3 _e128 = color_8;
    vec4 _e131 = u.colorB;
    color_8 = mix(_e128, _e131.xyz, upperVeil * 0.7);
    vec3 _e136 = color_8;
    vec4 _e139 = u.colorC;
    color_8 = mix(_e136, _e139.xyz, lowerVeil * 0.62);
    vec3 _e144 = color_8;
    vec4 _e147 = u.colorB;
    vec4 _e151 = u.colorC;
    color_8 = _e144 + ((mix(_e147.xyz, _e151.xyz, 0.46) * membrane) * 0.34);
    vec3 _e159 = color_8;
    vec4 _e162 = u.highlightColor;
    color_8 = _e159 + ((_e162.xyz * crest) * 0.14);
    vec3 _e168 = color_8;
    color_8 = _e168 * (0.58 + (0.42 * depth));
    vec3 _e174 = color_8;
    vec3 _e175 = glsFinishPresetFluid(_e174, p_15, u);
    return _e175;
}

vec3 glsBlueDropFluid(
    vec2 p,
    float t,
    Uniforms u
) {
    float depth = sqrt(max(1.0 - clamp(dot(p, p), 0.0, 1.0), 0.0));
    vec2 q = p * mix(0.72, 1.0, depth * 0.62 + 0.38);
    q = glsRotate(q, -0.24 + 0.06 * sin(t * 0.17));
    float scale = 1.0 + u.zoom * 1.12;
    float blur = 0.012 + 0.006 * u.zoom;
    vec2 driftA = lqFbm(q * 1.28 + vec2(t * 0.095, -t * 0.034), blur * 1.28);
    vec2 driftB = lqFbm(glsRotate(q, 1.08) * 1.62
                                 + vec2(-t * 0.042, t * 0.078), blur * 1.62);
    vec2 flowed = q + vec2(driftA.x - 0.5, driftB.x - 0.5)
                               * (0.24 + u.warp * 0.1);
    flowed.x += sin(flowed.y * 2.15 + t * 0.24) * (0.035 + u.warp * 0.012);
    flowed.y += sin(flowed.x * 1.38 - t * 0.18) * (0.045 + u.warp * 0.01);
    vec2 body = lqFbm(flowed * scale + vec2(t * 0.025, -t * 0.018), blur * scale);
    float marbleScale = 1.72 + u.zoom * 0.9;
    float marble = lqRidgeS(lqFbm(flowed * marbleScale
                                  + vec2(2.7, -t * 0.035), blur * marbleScale),
                            0.8 + u.sharp * 0.46);
    float value = clamp(mix(body.x, body.x * 0.62 + marble * 0.58, u.ridgeAmt), 0.0, 1.0);
    vec3 color = lqRamp(value, u.colorA.xyz, u.colorB.xyz, u.colorC.xyz, u.colorD.xyz, u);
    vec3 surface = normalize(vec3(p.x, p.y, depth));
    vec3 direction = normalize(vec3(-0.48, 0.62, 0.92));
    float light = pow(max(dot(surface, direction), 0.0), 3.2);
    color = mix(color, u.highlightColor.xyz, light * (0.035 + 0.05 * u.shade));
    color *= 0.74 + 0.26 * depth;
    return glsFinishPresetFluid(color, p, u);
}

vec3 glsVioletEmberFluid(
    vec2 p,
    float t,
    Uniforms u
) {
    float scale = 1.08 + u.zoom * 1.18;
    float blur = 0.011 + 0.005 * u.zoom;
    float radius = length(p);
    float twist = t * 0.055 + radius * (0.72 + u.warp * 0.11)
                  + 0.08 * sin(t * 0.31 + radius * 4.0);
    vec2 q = glsRotate(p * scale, twist);
    vec2 low = lqFbm(q * 1.18 + vec2(t * 0.068, -t * 0.105), blur * 1.18);
    vec2 cross = lqFbm(glsRotate(q, -1.12) * 1.52
                                + vec2(-t * 0.094, t * 0.042)
                                + vec2(low.x * 1.35, -low.x * 0.72), blur * 1.52);
    vec2 warped = q + vec2(low.x - 0.5, cross.x - 0.5)
                              * (0.3 + u.warp * 0.12);
    vec2 melt = lqFbm(warped * 1.34
                               + vec2(cross.x * 1.48, low.x * 1.12), blur * 1.34);
    float veinScale = 2.05 + u.zoom * 0.72;
    float veins = lqRidgeS(lqFbm(warped * veinScale
                                 + vec2(-2.1, t * 0.052), blur * veinScale),
                           0.82 + u.sharp * 0.58);
    float heat = smoothstep(0.18, 0.92,
                                   melt.x * (0.72 - u.ridgeAmt * 0.16)
                                   + veins * (0.32 + u.ridgeAmt * 0.5));
    vec3 color = lqRamp(heat, u.colorA.xyz, u.colorB.xyz, u.colorC.xyz, u.colorD.xyz, u);
    float pulse = 0.94 + 0.06 * sin(t * 0.44 + melt.x * 5.0);
    color *= pulse;
    color = mix(color, u.highlightColor.xyz, pow(veins, 4.0) * 0.045);
    return glsFinishPresetFluid(color, p, u);
}

vec3 glsRefractiveBlobFluid(
    vec2 p,
    float t,
    Uniforms u
) {
    float radial2 = clamp(dot(p, p), 0.0, 1.0);
    float depth = sqrt(max(1.0 - radial2, 0.0));
    float scale = 0.82 + u.zoom * 1.08;
    float blur = 0.012 + 0.005 * u.zoom;
    vec2 q = glsRotate(p * scale, 0.08 * sin(t * 0.17));
    vec2 driftA = lqFbm(
        q * 1.16 + vec2(t * 0.052, -t * 0.078), blur * 1.16);
    vec2 driftB = lqFbm(
        glsRotate(q, 1.21) * 1.34 + vec2(-t * 0.064, t * 0.041),
        blur * 1.34);
    q += vec2(driftA.x - 0.5, driftB.x - 0.5)
       * (0.34 + u.warp * 0.105);

    vec2 body = lqFbm(
        q * 1.42 + vec2(driftB.x * 0.82, driftA.x * 0.66),
        blur * 1.42);
    float ribbonPhase = q.y * (2.2 + u.warp * 0.11)
                      + sin(q.x * 1.72 - t * 0.19) * 0.92
                      + sin((q.x + q.y) * 1.08 + t * 0.13) * 0.46;
    float ribbon = pow(
        clamp(1.0 - abs(sin(ribbonPhase)), 0.0, 1.0),
        0.82 + u.sharp * 0.23);
    float fold = lqRidgeS(
        lqFbm(q * 2.05 + vec2(2.8, -t * 0.037), blur * 2.05),
        0.9 + u.sharp * 0.32);
    float value = clamp(
        body.x * 0.5 + driftA.x * 0.16
        + ribbon * (0.2 + u.ridgeAmt * 0.2)
        + fold * u.ridgeAmt * 0.18, 0.0, 1.0);

    vec3 color = lqRamp(
        value, u.colorA.xyz, u.colorB.xyz, u.colorC.xyz, u.colorD.xyz, u);
    float caustic = pow(ribbon, 3.1) * (0.24 + 0.28 * u.ridgeAmt)
                  + pow(fold, 4.2) * 0.08;
    color = mix(color, u.colorD.xyz, clamp(caustic, 0.0, 0.52));
    color *= 0.7 + depth * 0.3;
    float key = pow(max(dot(
        normalize(vec3(p, depth)),
        normalize(vec3(-0.42, 0.58, 0.9))), 0.0), 4.0);
    color = mix(color, u.highlightColor.xyz, key * 0.055);
    return glsFinishPresetFluid(color, p, u);
}

vec3 glsParticleRibbonFluid(
    vec2 p,
    float t,
    Uniforms u
) {
    return vec3(0.0);
}

vec3 glsPresetFluid(
    vec2 p_16,
    int style,
    float t_13,
    Uniforms u
) {
    if (style == 9) {
        vec3 _e5 = glsSiriFluid(p_16, t_13, u);
        return _e5;
    }
    if (style == 10) {
        vec3 _e8 = glsAuroraFluid(p_16, t_13, u);
        return _e8;
    }
    if (style == 11) {
        vec3 _e11 = glsPlasmaFluid(p_16, t_13, u);
        return _e11;
    }
    if (style == 12) {
        vec3 _e14 = glsChromeFluid(p_16, t_13, u);
        return _e14;
    }
    if (style == 13) {
        vec3 _e17 = glsOpalFluid(p_16, t_13, u);
        return _e17;
    }
    if (style == 14) {
        vec3 _e20 = glsSpectrumFluid(p_16, t_13, u);
        return _e20;
    }
    if (style == 15) {
        vec3 _e23 = glsFrostFluid(p_16, t_13, u);
        return _e23;
    }
    if (style == 19) {
        vec3 _e26 = glsVoiceWaveFluid(p_16, t_13, u);
        return _e26;
    }
    if (style == 20) {
        return glsBlueDropFluid(p_16, t_13, u);
    }
    if (style == 21) {
        return glsVioletEmberFluid(p_16, t_13, u);
    }
    if (style == 22) {
        return glsChromaticMetalFluid(p_16, t_13, u);
    }
    if (style == 23) {
        return glsRefractiveBlobFluid(p_16, t_13, u);
    }
    if (style == 24) {
        return glsParticleRibbonFluid(p_16, t_13, u);
    }
    vec3 _e27 = glsFrostFluid(p_16, t_13, u);
    return _e27;
}

vec3 glsFluid(
    vec2 fu,
    int md,
    float t_14,
    Uniforms u
) {
    vec3 fcol = vec3(0);
    vec2 pp = vec2(0);
    float v_2 = float(0);
    float df = length(fu);
    vec4 _e6 = u.colorA;
    vec3 cA_1 = _e6.xyz;
    vec4 _e10 = u.colorB;
    vec3 cB_1 = _e10.xyz;
    vec4 _e14 = u.colorC;
    vec3 cC_1 = _e14.xyz;
    vec4 _e18 = u.colorD;
    vec3 cD_1 = _e18.xyz;
    float _e24 = u.glassEnabled;
    float blurSigma = (_e24 > 0.5) ? GL_BSIG_GLASS : GL_BSIG_CLEAR;
    float _e30 = u.zoom;
    float sp = blurSigma * _e30;
    float sw = (sp * 1.1) * GL_KWA;
    if (md < 0) {
        float _e41 = u.zoom;
        pp = fu * _e41;
        float _e46 = pp.y;
        pp.y = _e46 + (t_14 * 0.05);
        vec2 _e50 = pp;
        vec2 _e58 = lqFbm((_e50 * 1.1) + vec2(0.0, t_14 * 0.09), sw);
        vec2 _e60 = pp;
        vec2 _e69 = lqFbm((_e60 * 1.1) + vec2(7.7, -(t_14) * 0.07), sw);
        vec2 w = vec2(_e58.x, _e69.x);
        vec2 _e72 = pp;
        float _e75 = u.warp;
        vec2 q_10 = _e72 + (_e75 * (w - vec2(0.5)));
        vec2 _e90 = lqFbm((q_10 * 1.5) + vec2(t_14 * 0.04, 0.0), sp * 1.5);
        vec2 _e98 = lqFbm((q_10 * 2.2) + vec2(3.1), sp * 2.2);
        float _e101 = u.sharp;
        float _e102 = lqRidgeS(_e98, _e101);
        float _e105 = lqStepS(_e90, 0.12, 0.88);
        float _e117 = u.ridgeAmt;
        float v_3 = mix(_e105, clamp((_e102 * 0.85) + (0.45 * _e90.x), 0.0, 1.0), _e117);
        vec3 _e119 = lqRamp(v_3, cA_1, cB_1, cC_1, cD_1, u);
        fcol = _e119;
    } else {
        float _e122 = u.zoom;
        vec2 pp_1 = fu * _e122;
        vec2 _e131 = lqFbm((pp_1 * 1.1) + vec2(0.0, t_14 * 0.09), sw);
        vec2 _e141 = lqFbm((pp_1 * 1.1) + vec2(7.7, -(t_14) * 0.07), sw);
        vec2 w_1 = vec2(_e131.x, _e141.x);
        float _e146 = u.warp;
        vec2 q_11 = pp_1 + (_e146 * (w_1 - vec2(0.5)));
        if (md == 0) {
            vec2 _e158 = lqFbm(q_11 * 2.2, sp * 2.2);
            float damp = exp(((-18.0 * _e158.y) * _e158.y) - ((24.5 * sp) * sp));
            v_2 = 0.5 + ((0.5 * damp) * sin(((q_11.x * 7.0) + (_e158.x * 6.0)) + (t_14 * 0.35)));
            float _e186 = v_2;
            vec2 _e195 = lqFbm((q_11 * 1.4) + vec2(t_14 * 0.03), sp * 1.4);
            v_2 = mix(_e186, _e195.x, 0.25);
            float _e199 = v_2;
            vec3 _e200 = lqRamp(_e199, cA_1, cB_1, cC_1, cD_1, u);
            fcol = _e200;
        } else {
            if (md == 1) {
                vec2 _e212 = lqFbm((q_11 * 1.4) + vec2(t_14 * 0.06, 0.0), sp * 1.4);
                float _e215 = u.sharp;
                float _e216 = lqRidgeS(_e212, _e215);
                vec2 _e226 = lqFbm((q_11 * 1.7) - vec2(0.0, t_14 * 0.05), sp * 1.7);
                float _e229 = u.sharp;
                float _e230 = lqRidgeS(_e226, _e229);
                float v_4 = _e216 * _e230;
                vec3 _e234 = lqRamp(pow(v_4, 0.7), cA_1, cB_1, cC_1, cD_1, u);
                fcol = _e234;
            } else {
                if (md == 6) {
                    vec2 _e247 = lqFbm((q_11 * 2.6) + vec2(t_14 * 0.025), sp * 2.6);
                    vec2 _e255 = lqFbm((q_11 * 1.3) + vec2(1.5 * _e247.x), sp * 1.3);
                    vec2 _e263 = lqFbm((q_11 * 2.1) + vec2(7.0), sp * 2.1);
                    float _e265 = lqRidgeS(_e263, 1.3);
                    float _e268 = lqStepS(_e255, 0.1, 0.9);
                    vec3 _e269 = lqRamp(_e268, cA_1, cB_1, cC_1, cD_1, u);
                    fcol = _e269;
                    vec3 _e270 = fcol;
                    fcol = _e270 * (1.0 - (0.18 * _e265));
                } else {
                    vec2 q2_ = q_11 + vec2(0.0, -(t_14) * 0.14);
                    vec2 _e294 = lqFbm((q2_ * 2.4) + vec2(0.0, -(t_14) * 0.05), sp * 2.4);
                    vec2 _e302 = lqFbm((q2_ * 1.6) + vec2(2.2 * _e294.x), sp * 1.6);
                    float _e304 = lqPowS(_e302, 1.5);
                    vec3 _e305 = lqRamp(_e304, cA_1, cB_1, cC_1, cD_1, u);
                    fcol = _e305;
                }
            }
        }
    }
    vec3 _e306 = fcol;
    vec4 _e309 = u.highlightColor;
    float _e313 = u.shade;
    fcol = mix(_e306, _e309.xyz, (_e313 * 0.3) * smoothstep(0.25, 1.25, dot(fu, vec2(-0.32, 0.78))));
    vec3 _e325 = fcol;
    float _e328 = u.shade;
    fcol = _e325 * (1.0 - ((_e328 * 0.42) * smoothstep(-0.05, 1.25, dot(fu, vec2(0.45, -0.62)))));
    vec3 _e342 = fcol;
    float _e345 = u.shade;
    fcol = _e342 * (1.0 - ((_e345 * 0.3) * smoothstep(0.72, 1.0, df)));
    vec3 _e355 = fcol;
    return clamp(_e355, vec3(0.0), vec3(1.0));
}

vec3 glsOver(
    vec3 dst,
    vec3 src,
    float a_3
) {
    float k_5 = clamp(a_3, 0.0, 1.0);
    return (src * k_5) + (dst * (1.0 - k_5));
}

float glsRefractionProfile(
    float t_15
) {
    float depth_1 = clamp(t_15, 0.0, 1.0);
    float circular = sqrt(max(1.0 - ((1.0 - depth_1) * (1.0 - depth_1)), 0.0));
    return 1.0 - circular;
}

float glsHighlightLobe(
    vec2 normal,
    vec2 direction,
    float cut,
    float power
) {
    float angular = clamp((dot(normal, direction) - cut) / max(1.0 - cut, 0.001), 0.0, 1.0);
    return pow(angular, power);
}

int naga_f2i32(float value) {
    return int(clamp(value, -2147483600.0, 2147483500.0));
}

vec2 glsContourWave(
    float angle_1,
    float t_16,
    Uniforms u
) {
    float _e4 = u.style;
    int style_1 = naga_f2i32(_e4 + 0.5);
    if (style_1 == 19) {
        float wave_1 = (sin((angle_1 * 2.0) + (t_16 * 0.27)) * 0.72) + (sin(((angle_1 * 4.0) - (t_16 * 0.16)) + 2.1) * 0.28);
        float slope = (cos((angle_1 * 2.0) + (t_16 * 0.27)) * 1.44) + (cos(((angle_1 * 4.0) - (t_16 * 0.16)) + 2.1) * 1.12);
        return vec2(wave_1, slope);
    }
    float wave_2 = ((sin((angle_1 * 3.0) + (t_16 * 0.62)) * 0.52) + (sin(((angle_1 * 5.0) - (t_16 * 0.41)) + 1.7) * 0.31)) + (sin(((angle_1 * 2.0) + (t_16 * 0.23)) + 3.1) * 0.17);
    float slope_1 = ((cos((angle_1 * 3.0) + (t_16 * 0.62)) * 1.56) + (cos(((angle_1 * 5.0) - (t_16 * 0.41)) + 1.7) * 1.55)) + (cos(((angle_1 * 2.0) + (t_16 * 0.23)) + 3.1) * 0.34);
    return vec2(wave_2, slope_1);
}

float glsContourStrength(
    Uniforms u
) {
    float _e2 = u.style;
    if (_e2 >= 18.5) {
        return 0.11;
    }
    float _e10 = u.style;
    return (_e10 >= 15.5) ? 0.16 : 0.09;
}

float glsContourScale(
    vec2 uv_1,
    float t_17,
    float amount,
    Uniforms u
) {
    if (amount <= 0.0) {
        return 1.0;
    }
    vec2 _e9 = glsContourWave(atan(uv_1.y, uv_1.x), t_17, u);
    float _e13 = glsContourStrength(u);
    return 1.0 + ((clamp(amount, 0.0, 1.0) * _e13) * _e9.x);
}

vec2 glsContourNormal(
    vec2 uv_2,
    float rad_1,
    float t_18,
    float amount_1,
    Uniforms u
) {
    float distance_1 = length(uv_2);
    if (distance_1 <= 0.0001) {
        return vec2(0.0);
    }
    vec2 radial = uv_2 / vec2(distance_1);
    vec2 _e14 = glsContourWave(atan(uv_2.y, uv_2.x), t_18, u);
    float _e18 = glsContourStrength(u);
    float slope_2 = (clamp(amount_1, 0.0, 1.0) * _e18) * _e14.y;
    vec2 tangent = vec2(-(radial.y), radial.x);
    return normalize(radial - (tangent * ((rad_1 * slope_2) / distance_1)));
}

vec2 glsRefractionNormal(
    vec2 base,
    vec2 p,
    float t,
    int style
) {
    if (style != 23) {
        return base;
    }
    vec2 tangent = vec2(-base.y, base.x);
    float a = lqFbm(
        p * 2.15 + vec2(t * 0.061, -t * 0.043), 0.018).x;
    float b = lqFbm(
        glsRotate(p, 1.37) * 2.55 + vec2(-t * 0.037, t * 0.052),
        0.021).x;
    float wave = (a - b) * 0.76
               + sin(atan(p.y, p.x) * 3.0 + t * 0.21) * 0.08;
    return normalize(base + tangent * wave);
}

vec4 orbGlassLiquidAnim(
    vec2 uv01_,
    Uniforms u
) {
    vec2 fc = vec2(uv01_.x, 1.0 - uv01_.y) * u.size;
    vec2 uv = (2.0 * fc - u.size)
                     / max(min(u.size.x, u.size.y), 1.0);
    float rad = max(u.radius, 0.05);
    float t = u.time * u.speed;
    int s = naga_f2i32(u.style + 0.5);
    bool emissionOnly = u.glassEnabled <= 0.5 && (s == 9 || s == 14 || s == 24);
    float contourRad = rad * glsContourScale(uv, t, u.contourDeform, u);

    if (length(uv) > contourRad * (1.01 + mfEdgeD(u.edgeSoftness))) {
        vec3 halo = mfEdgeGlow(vec3(0.0), uv, vec2(0.0),
                                         contourRad, u.edgeSoftness, u.edgeGlow,
                                         u.glowColor.xyz);
        halo = clamp(halo, vec3(0.0), vec3(1.0));
        float haloAlpha = max(halo.x, max(halo.y, halo.z));
        return vec4(halo, haloAlpha);
    }

    vec2 p = uv / contourRad;
    float pd = length(p);
    vec2 fu = p / GL_FU;
    int md = -1;
    if (s == 1) { md = 1; }
    else if (s == 3 || s == 8) { md = 7; }
    else if (s == 5) { md = 6; }
    else if (s == 7) { md = 0; }

    float clearFa = 1.0 - smoothstep(GL_CLEAR_EA, GL_CLEAR_EB, pd);
    vec2 contourNormal = glsContourNormal(uv, rad, t, u.contourDeform, u);
    vec2 normal = glsRefractionNormal(contourNormal, p, t, s);
    float edgeDepth = max(1.0 - pd, 0.0);
    float refractionWidth = 0.015 + 0.95 * clamp(u.shellMidAlpha, 0.0, 1.0);
    float refractionT = edgeDepth / max(refractionWidth, 0.001);
    float refractionProfile = pow(glsRefractionProfile(refractionT), 0.68);
    float refractionAmount = 1.6 * clamp(u.glassOpacity, 0.0, 1.0)
                           * refractionProfile;
    vec2 refractedP = p - normal * refractionAmount;
    vec3 fcol = vec3(0.0);

    if (clearFa > 0.0) {
        if (s >= 9) {
            if (u.glassEnabled > 0.5) {
                float channelSplit = 0.14 * clamp(u.gloss, 0.0, 2.0)
                                   * clamp(u.glassOpacity, 0.0, 1.0)
                                   * refractionProfile;
                vec3 redSample = glsPresetFluid(refractedP - normal * channelSplit, s, t, u);
                vec3 greenSample = glsPresetFluid(refractedP, s, t, u);
                vec3 blueSample = glsPresetFluid(refractedP + normal * channelSplit, s, t, u);
                fcol = vec3(redSample.x, greenSample.y, blueSample.z);
            } else {
                fcol = glsPresetFluid(p, s, t, u);
            }
        } else {
            fcol = glsFluid(fu, md, t, u);
        }
    }

    float lum = dot(fcol, vec3(0.213, 0.715, 0.072));
    vec3 clearSat = clamp(
        vec3(lum) + (fcol - vec3(lum)) * 1.22,
        vec3(0.0), vec3(1.0));
    bool particleGlassOverlay = s == 24;
    vec3 col = particleGlassOverlay
        ? vec3(0.0)
        : glsOver(u.canvasColor.xyz, clearSat, 0.99 * clearFa);
    if (emissionOnly) {
        float signal = max(clearSat.x, max(clearSat.y, clearSat.z));
        float emissionCoverage = smoothstep(0.025, 0.16, signal);
        col = clearSat * emissionCoverage;
    }

    if (u.glassEnabled > 0.5) {
        float surfaceWidth = particleGlassOverlay
            ? 0.09 + 0.12 * clamp(u.shellEdgeAlpha, 0.0, 1.0)
            : 0.026 + 0.055 * clamp(u.shellEdgeAlpha, 0.0, 1.0);
        float surfaceBand = (1.0 - smoothstep(0.0, surfaceWidth, edgeDepth)) * clearFa;
        float opticalRim = pow(surfaceBand, particleGlassOverlay ? 1.3 : 1.8);
        float innerRimAlpha = !particleGlassOverlay
            ? opticalRim * u.glassOpacity * 0.45
            : opticalRim * u.glassOpacity * 0.14;
        col = glsOver(col, u.shellInner.xyz, innerRimAlpha);

        vec2 coolDirection = normalize(vec2(0.84, 0.54));
        vec2 warmDirection = normalize(vec2(-0.62, -0.78));
        float coolSplit = glsHighlightLobe(normal, coolDirection, -0.32, 1.8);
        float warmSplit = glsHighlightLobe(normal, warmDirection, -0.28, 2.0);
        float dispersion = opticalRim * clamp(u.gloss, 0.0, 2.0)
                         * (0.8 + 0.8 * u.shellEdgeAlpha);
        col = glsOver(col, u.shellMid.xyz, dispersion * coolSplit);
        col = glsOver(col, u.shellEdge.xyz, dispersion * warmSplit);

        float edgeShadow = opticalRim * (0.015 + 0.15 * u.shellEdgeAlpha)
                         * (0.15 + 0.85 * max(
                            dot(normal, vec2(0.45, -0.89)), 0.0));
        col *= 1.0 - edgeShadow;

        vec2 keyDirection = normalize(vec2(-0.68, 0.73));
        vec2 fillDirection = normalize(vec2(0.74, -0.67));
        float key = opticalRim * glsHighlightLobe(normal, keyDirection, 0.2, 2.8)
                  * clamp(u.sheen, 0.0, 2.0) * 1.4;
        float fill = opticalRim * glsHighlightLobe(normal, fillDirection, 0.4, 3.6)
                   * clamp(u.sheen, 0.0, 2.0) * 1.0;
        col = glsOver(col, u.sheenColor.xyz, key);
        col = glsOver(col, u.specColor.xyz, fill);
    }

    float ballA = 1.0 - smoothstep(
        0.99 - mfEdgeD(u.edgeSoftness),
        1.01 + mfEdgeD(u.edgeSoftness), pd);
    col = clamp(col * max(u.exposure, 0.0),
                       vec3(0.0), vec3(1.0)) * ballA;
    vec3 edged = mfEdgeGlow(col, uv, vec2(0.0), contourRad,
                                     u.edgeSoftness, u.edgeGlow, u.glowColor.xyz);
    vec3 finalColor = clamp(
        edged, vec3(0.0), vec3(1.0));
    float emissionAlpha = max(finalColor.x, max(finalColor.y, finalColor.z));
    float sphereAlpha = clamp(max(ballA, emissionAlpha), 0.0, 1.0);
    float finalAlpha = (emissionOnly || particleGlassOverlay)
        ? emissionAlpha
        : sphereAlpha;
    return vec4(finalColor, finalAlpha);
}
