// Adapted from Orb, https://github.com/LerSent001/orb
// Copyright (c) 2026 LerSent001. MIT License: ORB-LICENSE.txt.
// Generated by tools/port_orb_shaders.py; edit the converter to regenerate.
#include "orb-liquid.glsl"

vec4 mainImage(vec2 uv01) {
    Uniforms u = orbUniforms();
    vec4 c = orbGlassLiquidAnim(uv01, u);
    vec2 fc = vec2(uv01.x, 1.0-uv01.y)*u.size;
    vec2 uv = (2.0*fc-u.size)/max(min(u.size.x,u.size.y),1.0);
    float contourRad = max(u.radius,0.05)*glsContourScale(uv,u.time*u.speed,u.contourDeform,u);
    vec2 q = (2.0*fc-u.size)/u.size;
    float feather = 2.0/max(min(u.size.x,u.size.y),1.0);
    float start = min(mix(contourRad,1.0,0.5),1.0-feather);
    c *= 1.0-smoothstep(start,1.0,max(abs(q.x),abs(q.y)));
    return vec4(c.a > 0.00001 ? c.rgb/c.a : vec3(0), c.a);
}
