// Adapted from Orb, https://github.com/LerSent001/orb
// Copyright (c) 2026 LerSent001. MIT License: ORB-LICENSE.txt.
// Generated by tools/port_orb_shaders.py; edit the converter to regenerate.
#include "orb-liquid.glsl"
vec2 prTextureUvFromOrb(
    vec2 p,
    float contourRad,
    Uniforms u
) {
    float minSize = max(min(u.size.x, u.size.y), 1.0);
    vec2 fc = (p * contourRad * minSize + u.size) * 0.5;
    return clamp(
        vec2(
            fc.x / max(u.size.x, 1.0),
            1.0 - fc.y / max(u.size.y, 1.0)),
        vec2(0.0),
        vec2(1.0));
}



vec4 orbComposite(vec2 uv01, Uniforms u) {
 vec4 direct = saturnSampleBuffer(uv01);
    if (u.glassEnabled <= 0.5) {
        return  direct ;
    }

    vec2 fc = vec2(uv01.x, 1.0 - uv01.y) * u.size;
    float minSize = max(min(u.size.x, u.size.y), 1.0);
    vec2 uv = (2.0 * fc - u.size) / minSize;
    float rad = max(u.radius, 0.05);
    float t = u.time * u.speed;
    float contourRad = rad * glsContourScale(uv, t, u.contourDeform, u);
    vec4 shell = orbGlassLiquidAnim(uv01, u);
    if (length(uv) > contourRad * (1.01 + mfEdgeD(u.edgeSoftness))) {
        return  shell ;
    }

    vec2 p = uv / contourRad;
    float pd = length(p);
    float clearFa = 1.0 - smoothstep(GL_CLEAR_EA, GL_CLEAR_EB, pd);
    vec2 normal = glsContourNormal(uv, rad, t, u.contourDeform, u);
    float edgeDepth = max(1.0 - pd, 0.0);
    float refractionWidth = 0.015 + 0.95 * clamp(u.shellMidAlpha, 0.0, 1.0);
    float refractionT = edgeDepth / max(refractionWidth, 0.001);
    float refractionProfile = pow(glsRefractionProfile(refractionT), 0.68);
    float refractionAmount = 1.6 * clamp(u.glassOpacity, 0.0, 1.0)
                           * refractionProfile;
    vec2 refractedP = p - normal * refractionAmount;
    float channelSplit = 0.14 * clamp(u.gloss, 0.0, 2.0)
                       * clamp(u.glassOpacity, 0.0, 1.0)
                       * refractionProfile;
    vec4 redSample = saturnSampleBuffer(prTextureUvFromOrb(refractedP - normal * channelSplit, contourRad, u));
    vec4 greenSample = saturnSampleBuffer(prTextureUvFromOrb(refractedP, contourRad, u));
    vec4 blueSample = saturnSampleBuffer(prTextureUvFromOrb(refractedP + normal * channelSplit, contourRad, u));
    float refractedAlpha = max(
        redSample.w,
        max(greenSample.w, blueSample.w)) * clearFa;
    vec4 refracted = vec4(
        vec3(redSample.x, greenSample.y, blueSample.z) * clearFa,
        refractedAlpha);
    return
        vec4(
            shell.xyz + refracted.xyz * (1.0 - shell.w),
            shell.w + refracted.w * (1.0 - shell.w))
    ;
}

vec4 mainImage(vec2 uv) { vec4 c=orbComposite(uv,orbUniforms()); return vec4(c.a>0.00001?c.rgb/c.a:vec3(0),clamp(c.a,0.0,1.0)); }
