// Adapted from Orb, https://github.com/LerSent001/orb
// Copyright (c) 2026 LerSent001. MIT License: ORB-LICENSE.txt.
// Generated by tools/port_orb_shaders.py; edit the converter to regenerate.
uniform float orb_speed;
uniform float orb_radius;
uniform float orb_zoom;
uniform float orb_warp;
uniform float orb_ridgeAmt;
uniform float orb_sharp;
uniform float orb_shade;
uniform float orb_sheen;
uniform float orb_gloss;
uniform float orb_shellMidAlpha;
uniform float orb_shellEdgeAlpha;
uniform float orb_exposure;
uniform float orb_style;
uniform float orb_edgeSoftness;
uniform float orb_edgeGlow;
uniform float orb_paletteCount;
uniform float orb_glassEnabled;
uniform float orb_glassOpacity;
uniform float orb_contourDeform;
uniform float orb_bandDensity;
uniform float orb_chromaticShift;
uniform float orb_metalScale;
uniform float orb_metalStretch;
uniform float orb_metalAngle;
uniform float orb_metalOffset;
uniform float orb_metalPhase;
uniform float orb_metalEvolution;
uniform float orb_metalRoughness;
uniform float orb_metalDepth;
uniform float orb_particleDensity;
uniform float orb_ribbonCount;
uniform float orb_ribbonWidth;
uniform float orb_ribbonTwist;
uniform float orb_ribbonFold;
uniform float orb_ribbonBreath;
uniform float orb_particleSize;
uniform float orb_particleBloom;
uniform vec4 orb_colorA;
uniform vec4 orb_colorB;
uniform vec4 orb_colorC;
uniform vec4 orb_colorD;
uniform vec4 orb_highlightColor;
uniform vec4 orb_shellInner;
uniform vec4 orb_shellMid;
uniform vec4 orb_shellEdge;
uniform vec4 orb_sheenColor;
uniform vec4 orb_specColor;
uniform vec4 orb_canvasColor;
uniform vec4 orb_glowColor;
uniform vec4 orb_paletteStop0;
uniform vec4 orb_paletteStop1;
uniform vec4 orb_paletteStop2;
uniform vec4 orb_paletteStop3;
uniform vec4 orb_paletteStop4;
uniform vec4 orb_paletteStop5;
uniform vec4 orb_paletteStop6;
uniform vec4 orb_paletteStop7;
uniform vec4 orb_paletteStop8;
uniform vec4 orb_paletteStop9;
uniform vec4 orb_paletteStop10;
uniform vec4 orb_paletteStop11;
struct Uniforms {
    vec2 size;
    float time;
    float speed;
    float radius;
    float zoom;
    float warp;
    float ridgeAmt;
    float sharp;
    float shade;
    float sheen;
    float gloss;
    float shellMidAlpha;
    float shellEdgeAlpha;
    float exposure;
    float style;
    float edgeSoftness;
    float edgeGlow;
    float paletteCount;
    float glassEnabled;
    float glassOpacity;
    float contourDeform;
    float bandDensity;
    float chromaticShift;
    float metalScale;
    float metalStretch;
    float metalAngle;
    float metalOffset;
    float metalPhase;
    float metalEvolution;
    float metalRoughness;
    float metalDepth;
    float particleDensity;
    float ribbonCount;
    float ribbonWidth;
    float ribbonTwist;
    float ribbonFold;
    float ribbonBreath;
    float particleSize;
    float particleBloom;
    vec4 colorA;
    vec4 colorB;
    vec4 colorC;
    vec4 colorD;
    vec4 highlightColor;
    vec4 shellInner;
    vec4 shellMid;
    vec4 shellEdge;
    vec4 sheenColor;
    vec4 specColor;
    vec4 canvasColor;
    vec4 glowColor;
    vec4 paletteStop0_;
    vec4 paletteStop1_;
    vec4 paletteStop2_;
    vec4 paletteStop3_;
    vec4 paletteStop4_;
    vec4 paletteStop5_;
    vec4 paletteStop6_;
    vec4 paletteStop7_;
    vec4 paletteStop8_;
    vec4 paletteStop9_;
    vec4 paletteStop10_;
    vec4 paletteStop11_;
};
Uniforms orbUniforms() { return Uniforms(u_resolution, u_time, orb_speed, orb_radius, orb_zoom, orb_warp, orb_ridgeAmt, orb_sharp, orb_shade, orb_sheen, orb_gloss, orb_shellMidAlpha, orb_shellEdgeAlpha, orb_exposure, orb_style, orb_edgeSoftness, orb_edgeGlow, orb_paletteCount, orb_glassEnabled, orb_glassOpacity, orb_contourDeform, orb_bandDensity, orb_chromaticShift, orb_metalScale, orb_metalStretch, orb_metalAngle, orb_metalOffset, orb_metalPhase, orb_metalEvolution, orb_metalRoughness, orb_metalDepth, orb_particleDensity, orb_ribbonCount, orb_ribbonWidth, orb_ribbonTwist, orb_ribbonFold, orb_ribbonBreath, orb_particleSize, orb_particleBloom, orb_colorA, orb_colorB, orb_colorC, orb_colorD, orb_highlightColor, orb_shellInner, orb_shellMid, orb_shellEdge, orb_sheenColor, orb_specColor, orb_canvasColor, orb_glowColor, orb_paletteStop0, orb_paletteStop1, orb_paletteStop2, orb_paletteStop3, orb_paletteStop4, orb_paletteStop5, orb_paletteStop6, orb_paletteStop7, orb_paletteStop8, orb_paletteStop9, orb_paletteStop10, orb_paletteStop11); }
const uint PR_U_SEGMENTS = 384u;
const uint PR_V_SEGMENTS = 96u;
const uint PR_PARTICLES_PER_LAYER = PR_U_SEGMENTS * PR_V_SEGMENTS;

float prHash(float value) {
    return fract(sin(value * 12.9898 + 78.233) * 43758.5453);
}

vec3 prRotateX(vec3 p, float angle) {
    float c = cos(angle);
    float s = sin(angle);
    return vec3(p.x, c * p.y - s * p.z, s * p.y + c * p.z);
}

vec3 prRotateY(vec3 p, float angle) {
    float c = cos(angle);
    float s = sin(angle);
    return vec3(c * p.x + s * p.z, p.y, -s * p.x + c * p.z);
}

vec3 prCurve(
    float theta,
    float layer,
    float phase,
    Uniforms u
) {
    float local = theta + layer * 0.11;
    float foldPhase = 2.0 * local + phase * (0.72 + layer * 0.025);
    float fold = clamp(u.ribbonFold, 0.0, 1.2);
    float radial = 0.4 + (0.085 + fold * 0.04) * cos(foldPhase);
    float orbit = local + phase * 0.13
                + sin(local - phase * 0.22 + layer) * fold * 0.13;
    float vertical = (0.235 + fold * 0.085) * sin(foldPhase)
                   + 0.055 * sin(local * 3.0 - phase * 0.46 + layer * 0.7);
    return vec3(radial * cos(orbit), vertical, radial * sin(orbit));
}

vec3 prPalette(float valueIn, Uniforms u) {
    float value = fract(valueIn) * 4.0;
    if (value < 1.0) return mix(u.colorA.xyz, u.colorB.xyz, value);
    if (value < 2.0) return mix(u.colorB.xyz, u.colorC.xyz, value - 1.0);
    if (value < 3.0) return mix(u.colorC.xyz, u.colorD.xyz, value - 2.0);
    return mix(u.colorD.xyz, u.colorA.xyz, value - 3.0);
}

SATURN_LOCATION(0) noperspective out vec2 prLocal;
SATURN_LOCATION(1) out vec3 prColor;
SATURN_LOCATION(2) out float prOpacity;

void main(){
Uniforms u=orbUniforms();
uint vertexIndex=uint(SATURN_VERTEX_ID), instanceIndex=uint(SATURN_INSTANCE_ID);
    const vec2 corners[6] = vec2[6](
        vec2(-1.0, -1.0), vec2(1.0, -1.0),
        vec2(-1.0, 1.0), vec2(-1.0, 1.0),
        vec2(1.0, -1.0), vec2(1.0, 1.0)
    );
    uint layerIndex = instanceIndex / PR_PARTICLES_PER_LAYER;
    uint particleIndex = instanceIndex % PR_PARTICLES_PER_LAYER;
    uint uIndex = particleIndex / PR_V_SEGMENTS;
    uint vIndex = particleIndex % PR_V_SEGMENTS;
    float layer = float(layerIndex);
    float random = prHash(float(instanceIndex));
    bool activeLayer = layer < floor(clamp(u.ribbonCount, 2.0, 6.0) + 0.5);

    float uCoord = (float(uIndex) + prHash(float(instanceIndex) + 11.0) * 0.56)
                 / float(PR_U_SEGMENTS);
    float vCoord = (float(vIndex) + prHash(float(instanceIndex) + 29.0) * 0.46)
                 / float(PR_V_SEGMENTS);
    float strip = vCoord * 2.0 - 1.0;
    float t = u.time * u.speed;
    float phase = t * 0.48;
    float arc = fract(uCoord + layer * 0.211 - phase * 0.019);
    float arcLength = 0.76 + 0.055 * sin(t * 0.23 + layer * 1.71);
    float arcPosition = arc / arcLength;
    float arcEnvelope = smoothstep(0.0, 0.075, arcPosition)
                      * (1.0 - smoothstep(0.88, 1.0, arcPosition));
    bool particleActive = activeLayer
               && arc <= arcLength
               && random <= clamp(u.particleDensity, 0.2, 1.0);
    float theta = uCoord * 6.28318530718;
    vec3 center = prCurve(theta, layer, phase, u);
    vec3 ahead = prCurve(theta + 0.006, layer, phase, u);
    vec3 tangent = normalize(ahead - center);
    vec3 radial = normalize(center + vec3(0.001, 0.013, 0.007));
    vec3 side = normalize(cross(tangent, radial));
    vec3 surfaceNormal = normalize(cross(side, tangent));
    float twist = theta * (0.72 + u.ribbonTwist * 0.58)
                + phase * 0.74 + layer * 1.17;
    vec3 ribbonDirection = normalize(
        side * cos(twist) + surfaceNormal * sin(twist));
    float widthEnvelope = (0.72 + 0.28
        * pow(sin(theta * 1.5 + phase + layer), 2.0))
        * mix(0.42, 1.0, sqrt(max(arcEnvelope, 0.0)));
    vec3 position = center
        + ribbonDirection * strip * u.ribbonWidth * 0.5 * widthEnvelope;

    float pulse = sin(t * 0.73 + layer * 1.71)
                + 0.44 * sin(t * 1.17 + layer * 0.83 + 1.2);
    position *= 1.0 + u.ribbonBreath * pulse * 0.16;
    float layerCenter = layer
        - (floor(clamp(u.ribbonCount, 2.0, 6.0) + 0.5) - 1.0) * 0.5;
    position = prRotateY(
        position, layerCenter * 0.24 + sin(t * 0.19 + layer * 1.3) * 0.055);
    position = prRotateX(
        position, layerCenter * 0.14 + cos(t * 0.17 + layer * 0.9) * 0.04);
    position = prRotateY(position, t * 0.105 + sin(t * 0.21) * 0.11);
    position = prRotateX(position, -0.2 + sin(t * 0.16 + layer * 0.1) * 0.16);

    float minSize = max(min(u.size.x, u.size.y), 1.0);
    float depthScale = 0.88 + position.z * 0.16;
    vec2 orbPosition = position.xy * u.radius * 1.45 * depthScale;
    vec2 clip = vec2(
        orbPosition.x * minSize / max(u.size.x, 1.0),
        orbPosition.y * minSize / max(u.size.y, 1.0));
    float canvasParticleScale = clamp(minSize / 640.0, 0.22, 1.0);
    float pointPixels = max(0.6, u.particleSize)
                      * (1.5 + u.particleBloom * 2.5)
                      * (0.92 + position.z * 0.18)
                      * canvasParticleScale;
    vec2 corner = corners[vertexIndex];
    vec2 pointOffset = corner * pointPixels * 2.0
                              / max(u.size, vec2(1.0));

    float colorPhase = uCoord * 0.32 + layer * 0.19 + phase * 0.025
                     + position.z * 0.08;
    float stripEdge = smoothstep(0.58, 1.0, abs(strip));
    float front = clamp(0.78 + position.z * 0.54, 0.5, 1.24);
    float baseOpacity = mix(0.025, 0.009,
        clamp(u.shade / 1.5, 0.0, 1.0));


    gl_Position = particleActive
        ? vec4(clip + pointOffset,
                        clamp(0.5 - position.z * 0.12, 0.05, 0.95), 1.0)
        : vec4(2.0, 2.0, 1.0, 1.0);
    prLocal = corner;
    prColor = pow(
        mix(prPalette(colorPhase, u), u.highlightColor.xyz, stripEdge * 0.56),
        vec3(0.72)) * front;
    prOpacity = particleActive
        ? baseOpacity
            * (0.72 + stripEdge * 1.28)
            * arcEnvelope
            * pow(canvasParticleScale, 1.35)
        : 0.0;

#ifdef SATURN_VULKAN
    gl_Position.y = -gl_Position.y;
#endif
}
