# generated by gen_enums.py — do not edit
import enum

# flet value string -> RRGGBB hex (no alpha)
MATERIAL = {
    "amber": "FFC107",
    "amber100": "FFECB3",
    "amber200": "FFE082",
    "amber300": "FFD54F",
    "amber400": "FFCA28",
    "amber50": "FFF8E1",
    "amber500": "FFC107",
    "amber600": "FFB300",
    "amber700": "FFA000",
    "amber800": "FF8F00",
    "amber900": "FF6F00",
    "amberaccent": "FFD740",
    "amberaccent100": "FFE57F",
    "amberaccent200": "FFD740",
    "amberaccent400": "FFC400",
    "amberaccent700": "FFAB00",
    "black": "000000",
    "blue": "2196F3",
    "blue100": "BBDEFB",
    "blue200": "90CAF9",
    "blue300": "64B5F6",
    "blue400": "42A5F5",
    "blue50": "E3F2FD",
    "blue500": "2196F3",
    "blue600": "1E88E5",
    "blue700": "1976D2",
    "blue800": "1565C0",
    "blue900": "0D47A1",
    "blueaccent": "448AFF",
    "blueaccent100": "82B1FF",
    "blueaccent200": "448AFF",
    "blueaccent400": "2979FF",
    "blueaccent700": "2962FF",
    "bluegrey": "607D8B",
    "bluegrey100": "CFD8DC",
    "bluegrey200": "B0BEC5",
    "bluegrey300": "90A4AE",
    "bluegrey400": "78909C",
    "bluegrey50": "ECEFF1",
    "bluegrey500": "607D8B",
    "bluegrey600": "546E7A",
    "bluegrey700": "455A64",
    "bluegrey800": "37474F",
    "bluegrey900": "263238",
    "brown": "795548",
    "brown100": "D7CCC8",
    "brown200": "BCAAA4",
    "brown300": "A1887F",
    "brown400": "8D6E63",
    "brown50": "EFEBE9",
    "brown500": "795548",
    "brown600": "6D4C41",
    "brown700": "5D4037",
    "brown800": "4E342E",
    "brown900": "3E2723",
    "cyan": "00BCD4",
    "cyan100": "B2EBF2",
    "cyan200": "80DEEA",
    "cyan300": "4DD0E1",
    "cyan400": "26C6DA",
    "cyan50": "E0F7FA",
    "cyan500": "00BCD4",
    "cyan600": "00ACC1",
    "cyan700": "0097A7",
    "cyan800": "00838F",
    "cyan900": "006064",
    "cyanaccent": "18FFFF",
    "cyanaccent100": "84FFFF",
    "cyanaccent200": "18FFFF",
    "cyanaccent400": "00E5FF",
    "cyanaccent700": "00B8D4",
    "deeporange": "FF5722",
    "deeporange100": "FFCCBC",
    "deeporange200": "FFAB91",
    "deeporange300": "FF8A65",
    "deeporange400": "FF7043",
    "deeporange50": "FBE9E7",
    "deeporange500": "FF5722",
    "deeporange600": "F4511E",
    "deeporange700": "E64A19",
    "deeporange800": "D84315",
    "deeporange900": "BF360C",
    "deeporangeaccent": "FF6E40",
    "deeporangeaccent100": "FF9E80",
    "deeporangeaccent200": "FF6E40",
    "deeporangeaccent400": "FF3D00",
    "deeporangeaccent700": "DD2C00",
    "deeppurple": "673AB7",
    "deeppurple100": "D1C4E9",
    "deeppurple200": "B39DDB",
    "deeppurple300": "9575CD",
    "deeppurple400": "7E57C2",
    "deeppurple50": "EDE7F6",
    "deeppurple500": "673AB7",
    "deeppurple600": "5E35B1",
    "deeppurple700": "512DA8",
    "deeppurple800": "4527A0",
    "deeppurple900": "311B92",
    "deeppurpleaccent": "7C4DFF",
    "deeppurpleaccent100": "B388FF",
    "deeppurpleaccent200": "7C4DFF",
    "deeppurpleaccent400": "651FFF",
    "deeppurpleaccent700": "6200EA",
    "green": "4CAF50",
    "green100": "C8E6C9",
    "green200": "A5D6A7",
    "green300": "81C784",
    "green400": "66BB6A",
    "green50": "E8F5E9",
    "green500": "4CAF50",
    "green600": "43A047",
    "green700": "388E3C",
    "green800": "2E7D32",
    "green900": "1B5E20",
    "greenaccent": "69F0AE",
    "greenaccent100": "B9F6CA",
    "greenaccent200": "69F0AE",
    "greenaccent400": "00E676",
    "greenaccent700": "00C853",
    "grey": "9E9E9E",
    "grey100": "F5F5F5",
    "grey200": "EEEEEE",
    "grey300": "E0E0E0",
    "grey350": "D6D6D6",
    "grey400": "BDBDBD",
    "grey50": "FAFAFA",
    "grey500": "9E9E9E",
    "grey600": "757575",
    "grey700": "616161",
    "grey800": "424242",
    "grey850": "303030",
    "grey900": "212121",
    "indigo": "3F51B5",
    "indigo100": "C5CAE9",
    "indigo200": "9FA8DA",
    "indigo300": "7986CB",
    "indigo400": "5C6BC0",
    "indigo50": "E8EAF6",
    "indigo500": "3F51B5",
    "indigo600": "3949AB",
    "indigo700": "303F9F",
    "indigo800": "283593",
    "indigo900": "1A237E",
    "indigoaccent": "536DFE",
    "indigoaccent100": "8C9EFF",
    "indigoaccent200": "536DFE",
    "indigoaccent400": "3D5AFE",
    "indigoaccent700": "304FFE",
    "lightblue": "03A9F4",
    "lightblue100": "B3E5FC",
    "lightblue200": "81D4FA",
    "lightblue300": "4FC3F7",
    "lightblue400": "29B6F6",
    "lightblue50": "E1F5FE",
    "lightblue500": "03A9F4",
    "lightblue600": "039BE5",
    "lightblue700": "0288D1",
    "lightblue800": "0277BD",
    "lightblue900": "01579B",
    "lightblueaccent": "40C4FF",
    "lightblueaccent100": "80D8FF",
    "lightblueaccent200": "40C4FF",
    "lightblueaccent400": "00B0FF",
    "lightblueaccent700": "0091EA",
    "lightgreen": "8BC34A",
    "lightgreen100": "DCEDC8",
    "lightgreen200": "C5E1A5",
    "lightgreen300": "AED581",
    "lightgreen400": "9CCC65",
    "lightgreen50": "F1F8E9",
    "lightgreen500": "8BC34A",
    "lightgreen600": "7CB342",
    "lightgreen700": "689F38",
    "lightgreen800": "558B2F",
    "lightgreen900": "33691E",
    "lightgreenaccent": "B2FF59",
    "lightgreenaccent100": "CCFF90",
    "lightgreenaccent200": "B2FF59",
    "lightgreenaccent400": "76FF03",
    "lightgreenaccent700": "64DD17",
    "lime": "CDDC39",
    "lime100": "F0F4C3",
    "lime200": "E6EE9C",
    "lime300": "DCE775",
    "lime400": "D4E157",
    "lime50": "F9FBE7",
    "lime500": "CDDC39",
    "lime600": "C0CA33",
    "lime700": "AFB42B",
    "lime800": "9E9D24",
    "lime900": "827717",
    "limeaccent": "EEFF41",
    "limeaccent100": "F4FF81",
    "limeaccent200": "EEFF41",
    "limeaccent400": "C6FF00",
    "limeaccent700": "AEEA00",
    "orange": "FF9800",
    "orange100": "FFE0B2",
    "orange200": "FFCC80",
    "orange300": "FFB74D",
    "orange400": "FFA726",
    "orange50": "FFF3E0",
    "orange500": "FF9800",
    "orange600": "FB8C00",
    "orange700": "F57C00",
    "orange800": "EF6C00",
    "orange900": "E65100",
    "orangeaccent": "FFAB40",
    "orangeaccent100": "FFD180",
    "orangeaccent200": "FFAB40",
    "orangeaccent400": "FF9100",
    "orangeaccent700": "FF6D00",
    "pink": "E91E63",
    "pink100": "F8BBD0",
    "pink200": "F48FB1",
    "pink300": "F06292",
    "pink400": "EC407A",
    "pink50": "FCE4EC",
    "pink500": "E91E63",
    "pink600": "D81B60",
    "pink700": "C2185B",
    "pink800": "AD1457",
    "pink900": "880E4F",
    "pinkaccent": "FF4081",
    "pinkaccent100": "FF80AB",
    "pinkaccent200": "FF4081",
    "pinkaccent400": "F50057",
    "pinkaccent700": "C51162",
    "purple": "9C27B0",
    "purple100": "E1BEE7",
    "purple200": "CE93D8",
    "purple300": "BA68C8",
    "purple400": "AB47BC",
    "purple50": "F3E5F5",
    "purple500": "9C27B0",
    "purple600": "8E24AA",
    "purple700": "7B1FA2",
    "purple800": "6A1B9A",
    "purple900": "4A148C",
    "purpleaccent": "E040FB",
    "purpleaccent100": "EA80FC",
    "purpleaccent200": "E040FB",
    "purpleaccent400": "D500F9",
    "purpleaccent700": "AA00FF",
    "red": "F44336",
    "red100": "FFCDD2",
    "red200": "EF9A9A",
    "red300": "E57373",
    "red400": "EF5350",
    "red50": "FFEBEE",
    "red500": "F44336",
    "red600": "E53935",
    "red700": "D32F2F",
    "red800": "C62828",
    "red900": "B71C1C",
    "redaccent": "FF5252",
    "redaccent100": "FF8A80",
    "redaccent200": "FF5252",
    "redaccent400": "FF1744",
    "redaccent700": "D50000",
    "teal": "009688",
    "teal100": "B2DFDB",
    "teal200": "80CBC4",
    "teal300": "4DB6AC",
    "teal400": "26A69A",
    "teal50": "E0F2F1",
    "teal500": "009688",
    "teal600": "00897B",
    "teal700": "00796B",
    "teal800": "00695C",
    "teal900": "004D40",
    "tealaccent": "64FFDA",
    "tealaccent100": "A7FFEB",
    "tealaccent200": "64FFDA",
    "tealaccent400": "1DE9B6",
    "tealaccent700": "00BFA5",
    "transparent": "000000",
    "white": "FFFFFF",
    "yellow": "FFEB3B",
    "yellow100": "FFF9C4",
    "yellow200": "FFF59D",
    "yellow300": "FFF176",
    "yellow400": "FFEE58",
    "yellow50": "FFFDE7",
    "yellow500": "FFEB3B",
    "yellow600": "FDD835",
    "yellow700": "FBC02D",
    "yellow800": "F9A825",
    "yellow900": "F57F17",
    "yellowaccent": "FFFF00",
    "yellowaccent100": "FFFF8D",
    "yellowaccent200": "FFFF00",
    "yellowaccent400": "FFEA00",
    "yellowaccent700": "FFD600",
}


class Colors(str, enum.Enum):
    AMBER = "amber"
    AMBER_100 = "amber100"
    AMBER_200 = "amber200"
    AMBER_300 = "amber300"
    AMBER_400 = "amber400"
    AMBER_50 = "amber50"
    AMBER_500 = "amber500"
    AMBER_600 = "amber600"
    AMBER_700 = "amber700"
    AMBER_800 = "amber800"
    AMBER_900 = "amber900"
    AMBER_ACCENT = "amberaccent"
    AMBER_ACCENT_100 = "amberaccent100"
    AMBER_ACCENT_200 = "amberaccent200"
    AMBER_ACCENT_400 = "amberaccent400"
    AMBER_ACCENT_700 = "amberaccent700"
    BLACK = "black"
    BLACK_12 = "black12"
    BLACK_26 = "black26"
    BLACK_38 = "black38"
    BLACK_45 = "black45"
    BLACK_54 = "black54"
    BLACK_87 = "black87"
    BLUE = "blue"
    BLUE_100 = "blue100"
    BLUE_200 = "blue200"
    BLUE_300 = "blue300"
    BLUE_400 = "blue400"
    BLUE_50 = "blue50"
    BLUE_500 = "blue500"
    BLUE_600 = "blue600"
    BLUE_700 = "blue700"
    BLUE_800 = "blue800"
    BLUE_900 = "blue900"
    BLUE_ACCENT = "blueaccent"
    BLUE_ACCENT_100 = "blueaccent100"
    BLUE_ACCENT_200 = "blueaccent200"
    BLUE_ACCENT_400 = "blueaccent400"
    BLUE_ACCENT_700 = "blueaccent700"
    BLUE_GREY = "bluegrey"
    BLUE_GREY_100 = "bluegrey100"
    BLUE_GREY_200 = "bluegrey200"
    BLUE_GREY_300 = "bluegrey300"
    BLUE_GREY_400 = "bluegrey400"
    BLUE_GREY_50 = "bluegrey50"
    BLUE_GREY_500 = "bluegrey500"
    BLUE_GREY_600 = "bluegrey600"
    BLUE_GREY_700 = "bluegrey700"
    BLUE_GREY_800 = "bluegrey800"
    BLUE_GREY_900 = "bluegrey900"
    BROWN = "brown"
    BROWN_100 = "brown100"
    BROWN_200 = "brown200"
    BROWN_300 = "brown300"
    BROWN_400 = "brown400"
    BROWN_50 = "brown50"
    BROWN_500 = "brown500"
    BROWN_600 = "brown600"
    BROWN_700 = "brown700"
    BROWN_800 = "brown800"
    BROWN_900 = "brown900"
    CYAN = "cyan"
    CYAN_100 = "cyan100"
    CYAN_200 = "cyan200"
    CYAN_300 = "cyan300"
    CYAN_400 = "cyan400"
    CYAN_50 = "cyan50"
    CYAN_500 = "cyan500"
    CYAN_600 = "cyan600"
    CYAN_700 = "cyan700"
    CYAN_800 = "cyan800"
    CYAN_900 = "cyan900"
    CYAN_ACCENT = "cyanaccent"
    CYAN_ACCENT_100 = "cyanaccent100"
    CYAN_ACCENT_200 = "cyanaccent200"
    CYAN_ACCENT_400 = "cyanaccent400"
    CYAN_ACCENT_700 = "cyanaccent700"
    DEEP_ORANGE = "deeporange"
    DEEP_ORANGE_100 = "deeporange100"
    DEEP_ORANGE_200 = "deeporange200"
    DEEP_ORANGE_300 = "deeporange300"
    DEEP_ORANGE_400 = "deeporange400"
    DEEP_ORANGE_50 = "deeporange50"
    DEEP_ORANGE_500 = "deeporange500"
    DEEP_ORANGE_600 = "deeporange600"
    DEEP_ORANGE_700 = "deeporange700"
    DEEP_ORANGE_800 = "deeporange800"
    DEEP_ORANGE_900 = "deeporange900"
    DEEP_ORANGE_ACCENT = "deeporangeaccent"
    DEEP_ORANGE_ACCENT_100 = "deeporangeaccent100"
    DEEP_ORANGE_ACCENT_200 = "deeporangeaccent200"
    DEEP_ORANGE_ACCENT_400 = "deeporangeaccent400"
    DEEP_ORANGE_ACCENT_700 = "deeporangeaccent700"
    DEEP_PURPLE = "deeppurple"
    DEEP_PURPLE_100 = "deeppurple100"
    DEEP_PURPLE_200 = "deeppurple200"
    DEEP_PURPLE_300 = "deeppurple300"
    DEEP_PURPLE_400 = "deeppurple400"
    DEEP_PURPLE_50 = "deeppurple50"
    DEEP_PURPLE_500 = "deeppurple500"
    DEEP_PURPLE_600 = "deeppurple600"
    DEEP_PURPLE_700 = "deeppurple700"
    DEEP_PURPLE_800 = "deeppurple800"
    DEEP_PURPLE_900 = "deeppurple900"
    DEEP_PURPLE_ACCENT = "deeppurpleaccent"
    DEEP_PURPLE_ACCENT_100 = "deeppurpleaccent100"
    DEEP_PURPLE_ACCENT_200 = "deeppurpleaccent200"
    DEEP_PURPLE_ACCENT_400 = "deeppurpleaccent400"
    DEEP_PURPLE_ACCENT_700 = "deeppurpleaccent700"
    ERROR = "error"
    ERROR_CONTAINER = "errorcontainer"
    GREEN = "green"
    GREEN_100 = "green100"
    GREEN_200 = "green200"
    GREEN_300 = "green300"
    GREEN_400 = "green400"
    GREEN_50 = "green50"
    GREEN_500 = "green500"
    GREEN_600 = "green600"
    GREEN_700 = "green700"
    GREEN_800 = "green800"
    GREEN_900 = "green900"
    GREEN_ACCENT = "greenaccent"
    GREEN_ACCENT_100 = "greenaccent100"
    GREEN_ACCENT_200 = "greenaccent200"
    GREEN_ACCENT_400 = "greenaccent400"
    GREEN_ACCENT_700 = "greenaccent700"
    GREY = "grey"
    GREY_100 = "grey100"
    GREY_200 = "grey200"
    GREY_300 = "grey300"
    GREY_400 = "grey400"
    GREY_50 = "grey50"
    GREY_500 = "grey500"
    GREY_600 = "grey600"
    GREY_700 = "grey700"
    GREY_800 = "grey800"
    GREY_900 = "grey900"
    INDIGO = "indigo"
    INDIGO_100 = "indigo100"
    INDIGO_200 = "indigo200"
    INDIGO_300 = "indigo300"
    INDIGO_400 = "indigo400"
    INDIGO_50 = "indigo50"
    INDIGO_500 = "indigo500"
    INDIGO_600 = "indigo600"
    INDIGO_700 = "indigo700"
    INDIGO_800 = "indigo800"
    INDIGO_900 = "indigo900"
    INDIGO_ACCENT = "indigoaccent"
    INDIGO_ACCENT_100 = "indigoaccent100"
    INDIGO_ACCENT_200 = "indigoaccent200"
    INDIGO_ACCENT_400 = "indigoaccent400"
    INDIGO_ACCENT_700 = "indigoaccent700"
    INVERSE_PRIMARY = "inverseprimary"
    INVERSE_SURFACE = "inversesurface"
    LIGHT_BLUE = "lightblue"
    LIGHT_BLUE_100 = "lightblue100"
    LIGHT_BLUE_200 = "lightblue200"
    LIGHT_BLUE_300 = "lightblue300"
    LIGHT_BLUE_400 = "lightblue400"
    LIGHT_BLUE_50 = "lightblue50"
    LIGHT_BLUE_500 = "lightblue500"
    LIGHT_BLUE_600 = "lightblue600"
    LIGHT_BLUE_700 = "lightblue700"
    LIGHT_BLUE_800 = "lightblue800"
    LIGHT_BLUE_900 = "lightblue900"
    LIGHT_BLUE_ACCENT = "lightblueaccent"
    LIGHT_BLUE_ACCENT_100 = "lightblueaccent100"
    LIGHT_BLUE_ACCENT_200 = "lightblueaccent200"
    LIGHT_BLUE_ACCENT_400 = "lightblueaccent400"
    LIGHT_BLUE_ACCENT_700 = "lightblueaccent700"
    LIGHT_GREEN = "lightgreen"
    LIGHT_GREEN_100 = "lightgreen100"
    LIGHT_GREEN_200 = "lightgreen200"
    LIGHT_GREEN_300 = "lightgreen300"
    LIGHT_GREEN_400 = "lightgreen400"
    LIGHT_GREEN_50 = "lightgreen50"
    LIGHT_GREEN_500 = "lightgreen500"
    LIGHT_GREEN_600 = "lightgreen600"
    LIGHT_GREEN_700 = "lightgreen700"
    LIGHT_GREEN_800 = "lightgreen800"
    LIGHT_GREEN_900 = "lightgreen900"
    LIGHT_GREEN_ACCENT = "lightgreenaccent"
    LIGHT_GREEN_ACCENT_100 = "lightgreenaccent100"
    LIGHT_GREEN_ACCENT_200 = "lightgreenaccent200"
    LIGHT_GREEN_ACCENT_400 = "lightgreenaccent400"
    LIGHT_GREEN_ACCENT_700 = "lightgreenaccent700"
    LIME = "lime"
    LIME_100 = "lime100"
    LIME_200 = "lime200"
    LIME_300 = "lime300"
    LIME_400 = "lime400"
    LIME_50 = "lime50"
    LIME_500 = "lime500"
    LIME_600 = "lime600"
    LIME_700 = "lime700"
    LIME_800 = "lime800"
    LIME_900 = "lime900"
    LIME_ACCENT = "limeaccent"
    LIME_ACCENT_100 = "limeaccent100"
    LIME_ACCENT_200 = "limeaccent200"
    LIME_ACCENT_400 = "limeaccent400"
    LIME_ACCENT_700 = "limeaccent700"
    ON_ERROR = "onerror"
    ON_ERROR_CONTAINER = "onerrorcontainer"
    ON_INVERSE_SURFACE = "oninversesurface"
    ON_PRIMARY = "onprimary"
    ON_PRIMARY_CONTAINER = "onprimarycontainer"
    ON_PRIMARY_FIXED = "onprimaryfixed"
    ON_PRIMARY_FIXED_VARIANT = "onprimaryfixedvariant"
    ON_SECONDARY = "onsecondary"
    ON_SECONDARY_CONTAINER = "onsecondarycontainer"
    ON_SECONDARY_FIXED = "onsecondaryfixed"
    ON_SECONDARY_FIXED_VARIANT = "onsecondaryfixedvariant"
    ON_SURFACE = "onsurface"
    ON_SURFACE_VARIANT = "onsurfacevariant"
    ON_TERTIARY = "ontertiary"
    ON_TERTIARY_CONTAINER = "ontertiarycontainer"
    ON_TERTIARY_FIXED = "ontertiaryfixed"
    ON_TERTIARY_FIXED_VARIANT = "ontertiaryfixedvariant"
    ORANGE = "orange"
    ORANGE_100 = "orange100"
    ORANGE_200 = "orange200"
    ORANGE_300 = "orange300"
    ORANGE_400 = "orange400"
    ORANGE_50 = "orange50"
    ORANGE_500 = "orange500"
    ORANGE_600 = "orange600"
    ORANGE_700 = "orange700"
    ORANGE_800 = "orange800"
    ORANGE_900 = "orange900"
    ORANGE_ACCENT = "orangeaccent"
    ORANGE_ACCENT_100 = "orangeaccent100"
    ORANGE_ACCENT_200 = "orangeaccent200"
    ORANGE_ACCENT_400 = "orangeaccent400"
    ORANGE_ACCENT_700 = "orangeaccent700"
    OUTLINE = "outline"
    OUTLINE_VARIANT = "outlinevariant"
    PINK = "pink"
    PINK_100 = "pink100"
    PINK_200 = "pink200"
    PINK_300 = "pink300"
    PINK_400 = "pink400"
    PINK_50 = "pink50"
    PINK_500 = "pink500"
    PINK_600 = "pink600"
    PINK_700 = "pink700"
    PINK_800 = "pink800"
    PINK_900 = "pink900"
    PINK_ACCENT = "pinkaccent"
    PINK_ACCENT_100 = "pinkaccent100"
    PINK_ACCENT_200 = "pinkaccent200"
    PINK_ACCENT_400 = "pinkaccent400"
    PINK_ACCENT_700 = "pinkaccent700"
    PRIMARY = "primary"
    PRIMARY_CONTAINER = "primarycontainer"
    PRIMARY_FIXED = "primaryfixed"
    PRIMARY_FIXED_DIM = "primaryfixeddim"
    PURPLE = "purple"
    PURPLE_100 = "purple100"
    PURPLE_200 = "purple200"
    PURPLE_300 = "purple300"
    PURPLE_400 = "purple400"
    PURPLE_50 = "purple50"
    PURPLE_500 = "purple500"
    PURPLE_600 = "purple600"
    PURPLE_700 = "purple700"
    PURPLE_800 = "purple800"
    PURPLE_900 = "purple900"
    PURPLE_ACCENT = "purpleaccent"
    PURPLE_ACCENT_100 = "purpleaccent100"
    PURPLE_ACCENT_200 = "purpleaccent200"
    PURPLE_ACCENT_400 = "purpleaccent400"
    PURPLE_ACCENT_700 = "purpleaccent700"
    RED = "red"
    RED_100 = "red100"
    RED_200 = "red200"
    RED_300 = "red300"
    RED_400 = "red400"
    RED_50 = "red50"
    RED_500 = "red500"
    RED_600 = "red600"
    RED_700 = "red700"
    RED_800 = "red800"
    RED_900 = "red900"
    RED_ACCENT = "redaccent"
    RED_ACCENT_100 = "redaccent100"
    RED_ACCENT_200 = "redaccent200"
    RED_ACCENT_400 = "redaccent400"
    RED_ACCENT_700 = "redaccent700"
    SCRIM = "scrim"
    SECONDARY = "secondary"
    SECONDARY_CONTAINER = "secondarycontainer"
    SECONDARY_FIXED = "secondaryfixed"
    SECONDARY_FIXED_DIM = "secondaryfixeddim"
    SHADOW = "shadow"
    SURFACE = "surface"
    SURFACE_BRIGHT = "surfacebright"
    SURFACE_CONTAINER = "surfacecontainer"
    SURFACE_CONTAINER_HIGH = "surfacecontainerhigh"
    SURFACE_CONTAINER_HIGHEST = "surfacecontainerhighest"
    SURFACE_CONTAINER_LOW = "surfacecontainerlow"
    SURFACE_CONTAINER_LOWEST = "surfacecontainerlowest"
    SURFACE_DIM = "surfacedim"
    SURFACE_TINT = "surfacetint"
    TEAL = "teal"
    TEAL_100 = "teal100"
    TEAL_200 = "teal200"
    TEAL_300 = "teal300"
    TEAL_400 = "teal400"
    TEAL_50 = "teal50"
    TEAL_500 = "teal500"
    TEAL_600 = "teal600"
    TEAL_700 = "teal700"
    TEAL_800 = "teal800"
    TEAL_900 = "teal900"
    TEAL_ACCENT = "tealaccent"
    TEAL_ACCENT_100 = "tealaccent100"
    TEAL_ACCENT_200 = "tealaccent200"
    TEAL_ACCENT_400 = "tealaccent400"
    TEAL_ACCENT_700 = "tealaccent700"
    TERTIARY = "tertiary"
    TERTIARY_CONTAINER = "tertiarycontainer"
    TERTIARY_FIXED = "tertiaryfixed"
    TERTIARY_FIXED_DIM = "tertiaryfixeddim"
    TRANSPARENT = "transparent"
    WHITE = "white"
    WHITE_10 = "white10"
    WHITE_12 = "white12"
    WHITE_24 = "white24"
    WHITE_30 = "white30"
    WHITE_38 = "white38"
    WHITE_54 = "white54"
    WHITE_60 = "white60"
    WHITE_70 = "white70"
    YELLOW = "yellow"
    YELLOW_100 = "yellow100"
    YELLOW_200 = "yellow200"
    YELLOW_300 = "yellow300"
    YELLOW_400 = "yellow400"
    YELLOW_50 = "yellow50"
    YELLOW_500 = "yellow500"
    YELLOW_600 = "yellow600"
    YELLOW_700 = "yellow700"
    YELLOW_800 = "yellow800"
    YELLOW_900 = "yellow900"
    YELLOW_ACCENT = "yellowaccent"
    YELLOW_ACCENT_100 = "yellowaccent100"
    YELLOW_ACCENT_200 = "yellowaccent200"
    YELLOW_ACCENT_400 = "yellowaccent400"
    YELLOW_ACCENT_700 = "yellowaccent700"
