"""Generate an honest constructor comparison from installed Flet and Saturn."""
from __future__ import annotations
import inspect
import sys
from importlib.metadata import version
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import flet
import saturn


def parameters(cls):
    names = set()
    for base in cls.__mro__:
        if base is object:
            break
        names.update(name for name, parameter in inspect.signature(base.__init__).parameters.items()
                     if name != "self" and parameter.kind not in (parameter.VAR_KEYWORD, parameter.VAR_POSITIONAL))
        if base is saturn.Control:
            break
    return names


def audit():
    result = []
    for name in sorted(saturn.__all__):
        local, reference = getattr(saturn, name), getattr(flet, name, None)
        if (name in ("Page", "Control", "View") or not inspect.isclass(local) or
                not issubclass(local, saturn.Control) or not inspect.isclass(reference)):
            continue
        expected = parameters(reference)
        available = parameters(local)
        rejected = set().union(*(getattr(base, "__unsupported_parameters__", set()) for base in local.__mro__))
        result.append((name, expected & available - rejected, expected - available,
                       expected & rejected, available - expected))
    return result


def names(values):
    return ", ".join(f"`{value}`" for value in sorted(values)) or "—"


def main():
    rows = audit()
    out = ["# Control parameter comparison", "",
           f"Reviewed on **2026-09-27** against installed **Flet {version('flet')}**. Generated by `python tools/audit_control_parameters.py` from the public constructor signatures and explicit unsupported-parameter declarations.", "",
           "This compares Saturn's existing shared visual controls. It does not add every control in the Flet catalog. A matching constructor name is an API surface measurement, not proof of Flutter pixel parity. Focused interaction and rendering checks cover the implemented behavior.", "",
           "Unknown arguments raise `TypeError`. Explicitly listed unsupported options reject non-default requests instead of silently storing them. Flet's internal initialization fields are excluded below.", "",
           "## Summary", "", "| Control | Shared implemented parameters | Missing parameters | Explicitly unsupported |",
           "| --- | ---: | ---: | ---: |"]
    internals = {"_i", "_c", "_internals", "_values"}
    totals = [0, 0, 0]
    for name, accepted, missing, unsupported, extra in rows:
        accepted -= internals
        missing -= internals
        for index, count in enumerate((len(accepted), len(missing), len(unsupported))):
            totals[index] += count
        out.append(f"| [{name}](#{name.lower()}) | {len(accepted)} | {len(missing)} | {len(unsupported)} |")
    out += ["", f"Across **{len(rows)} controls**: **{totals[0]}** shared parameter occurrences implemented, **{totals[1]}** missing, and **{totals[2]}** explicitly unsupported. Common inherited parameters occur once per control in these totals.", "",
            "## Shared behavior and limits", "",
            "- Base controls: layout dimensions/margins/Stack edges, visibility/disabled/opacity, inherited RTL, references, aspect ratio, focus eligibility, mouse cursors, size events, rotation/scale/offset and implicit animations.",
            "- Input controls: selection/filtering/multiline editing, focus/keyboard interaction, state-dependent appearance and bounded dropdown menus; desktop behavior is tested.",
            "- Layout and graphics: wrapping Rows/Columns, Stack fitting, scroll culling, image fitting/repeating and cached gradients. GPU transforms retain texture UVs and analytic shape edges.",
            "- `semantics_label` is metadata. Saturn does not yet expose a native accessibility tree. Image filter-quality requests map to the available cached smooth/nearest sampling paths; they are not Flutter's exact filter kernels.",
            "- Shader and Subpage are Saturn extensions; see [Shaders](./shaders.md) and [Subpages](./subpages.md). Page and native Window are audited separately in [Page comparison](./page-properties-comparison.md).", ""]
    for name, accepted, missing, unsupported, extra in rows:
        out += [f"## {name}", "", "**Shared implemented:** " + names(accepted-internals) + ".", "",
                "**Missing:** " + names(missing-internals) + ".", "",
                "**Explicitly unsupported:** " + names(unsupported) + ".", "",
                "**Saturn extensions:** " + names(extra-internals) + ".", ""]
    path = ROOT / "docs/control-parameters-comparison.md"
    path.write_text("\n".join(out), encoding="utf-8")
    print(f"Generated {path}: {len(rows)} controls, {totals}")


if __name__ == "__main__":
    main()
