"""Runnable, source-backed examples used by the control reference pages.

Each snippet receives ``page`` and the imported ``saturn`` module. The same
snippet is rendered to the image shown immediately above it in the docs.
"""

EXAMPLES = {
    "Text": 'page.add(saturn.Text("Hello, Saturn", size=30, weight=saturn.FontWeight.BOLD))',
    "Row": 'page.add(saturn.Row([saturn.Icon(saturn.Icons.STAR), saturn.Text("In one row"), saturn.FilledButton("Open")], spacing=16))',
    "Column": 'page.add(saturn.Column([saturn.Text("First line"), saturn.Text("Second line"), saturn.FilledButton("Continue")], spacing=14))',
    "Container": 'page.add(saturn.Container(saturn.Text("A decorated container"), padding=24, bgcolor=saturn.Colors.PRIMARY_CONTAINER, border_radius=16))',
    "Stack": 'page.add(saturn.Stack([saturn.Container(width=230, height=110, bgcolor=saturn.Colors.PRIMARY_CONTAINER, border_radius=16), saturn.Text("Layered content", left=20, top=36)], width=230, height=110))',
    "Divider": 'page.add(saturn.Column([saturn.Text("Above"), saturn.Divider(), saturn.Text("Below")], width=360))',
    "Icon": 'page.add(saturn.Icon(saturn.Icons.FAVORITE, size=56, color=saturn.Colors.PRIMARY))',
    "Image": 'page.add(saturn.Image("examples/assets/test_img.png", width=300, height=150, border_radius=12))',
    "Card": 'page.add(saturn.Card(saturn.Container(saturn.Text("Card content"), padding=24), elevation=3))',
    "ListView": 'page.add(saturn.ListView([saturn.Text(f"Item {i}") for i in range(1, 6)], spacing=12, width=320, height=180))',
    "GestureDetector": 'page.add(saturn.GestureDetector(saturn.Container(saturn.Text("Tap this surface"), padding=20, bgcolor=saturn.Colors.PRIMARY_CONTAINER, border_radius=12), on_tap=lambda event: None))',
    "ListItem": 'page.add(saturn.ListItem("Your library", supporting="24 saved items", leading=saturn.Icon(saturn.Icons.FOLDER), width=400))',
    "ProgressBar": 'page.add(saturn.ProgressBar(0.65, width=320))',
    "ProgressRing": 'page.add(saturn.ProgressRing(0.65))',
    "Button": 'page.add(saturn.Button("Open project", icon=saturn.Icons.FOLDER_OPEN))',
    "ElevatedButton": 'page.add(saturn.ElevatedButton("Elevated action", icon=saturn.Icons.ADD))',
    "FilledButton": 'page.add(saturn.FilledButton("Continue", icon=saturn.Icons.ARROW_FORWARD))',
    "FilledTonalButton": 'page.add(saturn.FilledTonalButton("Save draft", icon=saturn.Icons.SAVE))',
    "OutlinedButton": 'page.add(saturn.OutlinedButton("Learn more"))',
    "TextButton": 'page.add(saturn.TextButton("Skip for now"))',
    "IconButton": 'page.add(saturn.IconButton(saturn.Icons.FAVORITE, icon_color=saturn.Colors.PRIMARY))',
    "ExpressiveButton": 'page.add(saturn.ExpressiveButton("Create", size="medium", icon=saturn.Icons.ADD))',
    "ExpressiveIconButton": 'page.add(saturn.ExpressiveIconButton(saturn.Icons.EDIT, size="large"))',
    "SplitButton": 'page.add(saturn.SplitButton("Run", icon=saturn.Icons.PLAY_ARROW))',
    "ButtonGroup": 'page.add(saturn.ButtonGroup([saturn.ExpressiveButton("Day"), saturn.ExpressiveButton("Week"), saturn.ExpressiveButton("Month")]))',
    "ToggleButton": 'page.add(saturn.ToggleButton("Selected", checked=True))',
    "ElevatedToggleButton": 'page.add(saturn.ElevatedToggleButton("Pinned", checked=True))',
    "FilledTonalToggleButton": 'page.add(saturn.FilledTonalToggleButton("Favorite", checked=True))',
    "OutlinedToggleButton": 'page.add(saturn.OutlinedToggleButton("Filter", checked=True))',
    "FloatingActionButton": 'page.add(saturn.FloatingActionButton(saturn.Icons.ADD))',
    "SmallFloatingActionButton": 'page.add(saturn.SmallFloatingActionButton(saturn.Icons.ADD))',
    "MediumFloatingActionButton": 'page.add(saturn.MediumFloatingActionButton(saturn.Icons.ADD))',
    "LargeFloatingActionButton": 'page.add(saturn.LargeFloatingActionButton(saturn.Icons.ADD))',
    "ExtendedFloatingActionButton": 'page.add(saturn.ExtendedFloatingActionButton("New document", icon=saturn.Icons.ADD))',
    "FloatingToolbar": 'page.add(saturn.FloatingToolbar(saturn.IconButton(saturn.Icons.EDIT), saturn.IconButton(saturn.Icons.SHARE), saturn.IconButton(saturn.Icons.DELETE)))',
    "HorizontalFloatingToolbar": 'page.add(saturn.HorizontalFloatingToolbar(saturn.IconButton(saturn.Icons.EDIT), saturn.IconButton(saturn.Icons.SHARE)))',
    "VerticalFloatingToolbar": 'page.add(saturn.VerticalFloatingToolbar(saturn.IconButton(saturn.Icons.EDIT), saturn.IconButton(saturn.Icons.DELETE)))',
    "FloatingActionButtonMenu": 'page.add(saturn.FloatingActionButtonMenu([saturn.FloatingActionButtonMenuItem("New document", icon=saturn.Icons.ADD), saturn.FloatingActionButtonMenuItem("Upload", icon=saturn.Icons.UPLOAD)], expanded=True))',
    "FloatingActionButtonMenuItem": 'page.add(saturn.FloatingActionButtonMenu([saturn.FloatingActionButtonMenuItem("Upload", icon=saturn.Icons.UPLOAD)], expanded=True))',
    "TextField": 'page.add(saturn.TextField("Saturn", label="Project name", width=340))',
    "Checkbox": 'page.add(saturn.Checkbox("Remember my choice", value=True))',
    "Switch": 'page.add(saturn.Switch("Notifications", value=True))',
    "Radio": 'page.add(saturn.Radio("standard", label="Standard"))',
    "RadioGroup": 'page.add(saturn.RadioGroup(saturn.Row([saturn.Radio("day", label="Day"), saturn.Radio("week", label="Week")]), value="day"))',
    "Dropdown": 'page.add(saturn.Dropdown(hint_text="Choose a format", options=[saturn.Option("pdf", text="PDF"), saturn.Option("csv", text="CSV")], width=300))',
    "Slider": 'page.add(saturn.Slider(value=0.65, width=320))',
    "AlertDialog": 'page.show_dialog(saturn.AlertDialog(title="Delete item?", content=saturn.Text("This action cannot be undone."), actions=[saturn.TextButton("Cancel"), saturn.FilledButton("Delete")]))',
    "SnackBar": 'page.show_dialog(saturn.SnackBar(saturn.Text("Saved successfully", color=saturn.Colors.ON_SURFACE), action="Undo", bgcolor=saturn.Colors.SURFACE_CONTAINER, duration=10000))',
    "LoadingIndicator": 'page.add(saturn.LoadingIndicator(contained=True, width=72, height=72))',
    "WavyProgressIndicator": 'page.add(saturn.WavyProgressIndicator(0.65, width=320))',
    "LinearWavyProgressIndicator": 'page.add(saturn.LinearWavyProgressIndicator(0.65, width=320))',
    "CircularWavyProgressIndicator": 'page.add(saturn.CircularWavyProgressIndicator(0.65))',
}
