"""Plain-language explanations for Saturn constructor parameters."""

DESCRIPTIONS = {
    # Layout, presentation, and shared control state.
    "align": "Alignment of the control within the available area.",
    "alignment": "Alignment of child content within a container or layout.",
    "bottom": "Distance from the bottom edge of a Stack.",
    "color": "Color of foreground content, text, or drawing.",
    "content": "Text or child control to display.",
    "controls": "Child controls in display order.",
    "data": "Custom data attached to the control or event.",
    "disabled": "Disable interaction and use the disabled appearance when True.",
    "expand": "Fill remaining parent space; a number sets the flex ratio.",
    "height": "Specified control height.",
    "horizontal_alignment": "Alignment on the horizontal or cross axis.",
    "items": "Items passed to a layout, group, or menu.",
    "left": "Distance from the left edge of a Stack.",
    "margin": "Space outside the control.",
    "offset": "Displacement applied beyond the layout position.",
    "opacity": "Control opacity, from 0 (transparent) to 1 (opaque).",
    "padding": "Space around the control's content.",
    "right": "Distance from the right edge of a Stack.",
    "rotate": "Rotation applied when drawing the control.",
    "scale": "Scale applied when drawing the control.",
    "spacing": "Space between adjacent child controls.",
    "item_extent": "Fixed item height, or width for a horizontal list; enables lazy layout.",
    "tight": "Size the layout closely to its children when True.",
    "top": "Distance from the top edge of a Stack.",
    "vertical_alignment": "Alignment on the vertical or cross axis.",
    "visible": "Hide the control when False.",
    "width": "Specified control width.",
    "x": "Horizontal coordinate or displacement.",
    "y": "Vertical coordinate or displacement.",
    "bgcolor": "Background color of the control or container.",
    "border": "Border settings.",
    "border_color": "Border color of the input area.",
    "border_radius": "Corner radius of the border or background.",
    "gradient": "Gradient used to fill the background.",
    "shadow": "Shadow outside the control.",
    "ink": "Whether to draw ripple feedback on clicks.",
    "elevation": "Surface elevation, which determines shadow strength.",
    "variant": "Visual variant of this control.",
    "horizontal": "Use horizontal scrolling or layout when True.",
    "vertical": "Use vertical layout when True.",
    "auto_scroll": "Scroll to the end automatically as content is added.",
    "leading": "Control or area before the main content.",
    "trailing": "Control or area after the main content.",
    "leading_indent": "Inset at the start of a divider.",
    "trailing_indent": "Inset at the end of a divider.",
    "thickness": "Thickness of a line or divider.",
    "fit": "How an image scales and crops within its bounds.",
    "src": "Image source: a local path, bytes, or data URI.",
    # Text, icons, and input.
    "value": "Current value of the control or data object.",
    "values": "Set of initial values.",
    "text": "Text displayed on the control.",
    "size": "Size of the text, icon, or control.",
    "weight": "Text font weight.",
    "italic": "Whether to use italic text.",
    "text_align": "Text alignment within the available width.",
    "max_lines": "Maximum number of lines to show or accept.",
    "no_wrap": "Prevent automatic line wrapping when True.",
    "selectable": "Whether text can be selected with the pointer.",
    "font_family": "Font family name registered on the page.",
    "letter_spacing": "Extra space between characters.",
    "overflow": "How to handle text beyond the available space.",
    "decoration": "Text or border decoration settings.",
    "icon": "Icon to draw.",
    "icon_color": "Foreground color of the icon.",
    "icon_size": "Displayed icon size.",
    "selected_icon": "Alternate icon shown when selected.",
    "label": "Label beside an input, option, or control.",
    "hint_text": "Hint shown before a value is entered or selected.",
    "text_size": "Font size of entered or selected text.",
    "text_style": "Style of entered or displayed text.",
    "password": "Mask entered characters when True.",
    "can_reveal_password": "Show a button for toggling password visibility.",
    "multiline": "Allow multiple lines of text input.",
    "read_only": "Display content without allowing edits when True.",
    "filled": "Use a filled input area.",
    "fill_color": "Background color of a filled input area.",
    "cursor_color": "Color of the text insertion cursor.",
    "options": "Options available in the dropdown menu.",
    "checked": "Whether the toggle button is currently selected.",
    "selected": "Whether the list item or icon button is selected.",
    "active_color": "Color used in the selected or on state.",
    "inactive_color": "Color used in the unselected state.",
    "thumb_color": "Color of the slider thumb.",
    "label_position": "Position of the label relative to the selection control.",
    "min": "Lower bound of the selectable range.",
    "max": "Upper bound of the selectable range.",
    "divisions": "Number of discrete steps in the range.",
    "round": "Number of decimal places in the displayed value.",
    "hover_color": "Color used in the hover state.",
    "mouse_cursor": "Pointer style shown on hover.",
    "drag_interval": "Minimum interval between consecutive drag events.",
    "hover_interval": "Minimum interval between consecutive hover events.",
    # Buttons, feedback, and animation.
    "autofocus": "Try to focus this control when the page opens.",
    "url": "Destination opened when the button is clicked.",
    "expressive": "Enable Expressive sizing and shape behavior.",
    "shape": "Base shape of the button.",
    "style": "Additional button style settings.",
    "connected": "Arrange buttons as a connected group.",
    "container_color": "Background color of a list item or container in its normal state.",
    "content_color": "Foreground color of list item content in its normal state.",
    "expanded_ratio": "Fraction by which a pressed button can grow in width.",
    "compression_limit": "Minimum size to which neighboring buttons can shrink.",
    "trailing_icon": "Icon in the secondary action area of a split button.",
    "headline": "Primary title of a list item.",
    "overline": "Small text above a list item's title.",
    "supporting": "Supporting text below a list item's title.",
    "selected_container_color": "List item background color when selected.",
    "selected_content_color": "List item foreground color when selected.",
    "expanded": "Whether the floating component or menu is expanded.",
    "vibrant": "Use a more vivid surface color for the toolbar.",
    "contained": "Place the loading indicator on a container background.",
    "bar_height": "Thickness of the linear progress bar.",
    "stroke_width": "Width of a progress ring or wave stroke.",
    "amplitude": "Height of the wave relative to its baseline.",
    "wavelength": "Distance between adjacent wave peaks.",
    "wave_speed": "Movement speed of the wave animation.",
    "title": "Title of a dialog, notification, or window.",
    "tooltip": "Short hint shown on hover.",
    "actions": "Action buttons at the bottom of a dialog.",
    "action": "Single action label or button on a snackbar.",
    "modal": "Prevent closing the dialog by clicking its barrier when True.",
    "open": "Whether the dialog or snackbar is open.",
    "duration": "Duration; the unit depends on the relevant class.",
    "animate": "Animation settings applied when a property changes.",
    "curve": "Curve used for animation interpolation.",
    "show_duration": "Duration of the entrance transition.",
    "exit_duration": "Duration of the exit transition.",
    "wait_duration": "Delay before the next display.",
    # Theme and geometry value objects.
    "color_scheme_seed": "Seed color used to generate the theme palette.",
    "bottom_left": "Corner radius at the bottom left.",
    "bottom_right": "Corner radius at the bottom right.",
    "top_left": "Corner radius at the top left.",
    "top_right": "Corner radius at the top right.",
    "angle": "Rotation angle.",
    "scale_x": "Horizontal scale factor.",
    "scale_y": "Vertical scale factor.",
    "blur_radius": "Shadow blur radius.",
    "spread_radius": "Distance the shadow outline expands outward.",
    "side": "Settings for one border side.",
    "origin": "Reference origin for the transformation.",
    "filter_quality": "Sampling quality used when scaling an image.",
    "gap_padding": "Space on either side of a floating label's border gap.",
    "size_constraints": "Allowed minimum and maximum dimensions.",
    "vertical_offset": "Additional vertical displacement.",
    "prefer_below": "Place the tooltip below the control when space permits.",
    "tap_to_dismiss": "Dismiss the tooltip when its area is tapped.",
    "trigger_mode": "Interaction that triggers the tooltip.",
    "enable_feedback": "Provide interaction feedback when enabled.",
    "exclude_from_semantics": "Exclude this control from accessibility semantics.",
    "transform_hit_tests": "Apply the geometry transform to the hit area as well.",
    "days": "Days in the duration.",
    "hours": "Hours in the duration.",
    "minutes": "Minutes in the duration.",
    "seconds": "Seconds in the duration.",
    "milliseconds": "Milliseconds in the duration.",
    "microseconds": "Microseconds in the duration.",
    # App, events, and file picker data.
    "app": "Current application instance supplied by the runtime.",
    "main": "Application entry point that receives a Page.",
    "backend": "Rendering backend to use. For saturn.run(), omission selects OpenGL unless SATURN_BACKEND overrides it.",
    "control": "Control that produced the event or holds the data.",
    "error": "Error message when an operation fails.",
    "message": "Text of the event or result message.",
    "method": "Name of the method that triggered the operation.",
    "name": "Name of the object, file, or resource.",
    "path": "Local file or directory path.",
    "file_name": "Suggested name for a saved file.",
    "bytes": "Byte content of the file or resource.",
    "files": "Files selected, uploaded, or returned.",
    "id": "Identifier of the file or object.",
    "key": "Key used to locate a control or service.",
    "ref": "Place to store a control or service reference.",
    "progress": "Completion progress of an upload or operation.",
    "upload_url": "Destination URL for file uploads.",
    # Constructor pass-through parameters.
    "args": "Positional arguments passed to the parent constructor.",
    "kwargs": "Keyword arguments passed to the parent constructor.",
    "base": "Keyword arguments passed to Control, such as width and height.",
    "_flet_ignored": "Extra arguments accepted for Flet compatibility without automatic behavior.",
}

EVENTS = {
    "on_action": "Callback called when the snackbar action is clicked.",
    "on_animation_end": "Callback called when the control animation finishes.",
    "on_blur": "Callback called when the control loses focus.",
    "on_change": "Callback called when the value changes.",
    "on_change_start": "Callback called when dragging or value editing begins.",
    "on_change_end": "Callback called when dragging or value editing ends.",
    "on_click": "Callback called when the control is clicked.",
    "on_dismiss": "Callback called when the dialog or snackbar closes.",
    "on_enter": "Callback called when the pointer enters the control.",
    "on_exit": "Callback called when the pointer leaves the control.",
    "on_focus": "Callback called when the control gains focus.",
    "on_hover": "Callback called when the pointer's hover state changes.",
    "on_long_press": "Callback called when the control is long pressed.",
    "on_result": "Callback called when a file selection or save returns a result.",
    "on_scroll": "Callback called when the list scrolls.",
    "on_select": "Callback called when a menu item or option is selected.",
    "on_submit": "Callback called when input is submitted.",
    "on_tap": "Callback called when a tap completes.",
    "on_tap_down": "Callback called when a press begins.",
    "on_trailing_click": "Callback called when the split button's secondary action is clicked.",
    "on_upload": "Callback called when file upload status changes.",
}

OVERRIDES = {
    ("run", "width"): "Initial application window width in pixels.",
    ("run", "height"): "Initial application window height in pixels.",
    ("run", "title"): "Application window title.",
    ("Text", "value"): "Text content to display.",
    ("TextField", "value"): "Initial or current text field content.",
    ("Checkbox", "value"): "Whether the checkbox is checked.",
    ("Slider", "value"): "Current slider value.",
    ("ProgressBar", "value"): "Progress, usually from 0 to 1; None means indeterminate.",
    ("ProgressRing", "value"): "Progress, usually from 0 to 1; None means indeterminate.",
    ("Dropdown", "value"): "Key of the currently selected option.",
    ("Image", "color"): "Optional image tint multiplied with the source pixels.",
    ("SnackBar", "duration"): "How many milliseconds the snackbar remains visible.",
    ("Container", "alignment"): "Alignment of content inside the container.",
    ("Row", "alignment"): "Arrangement of children along the horizontal main axis.",
    ("Column", "alignment"): "Arrangement of children along the vertical main axis.",
    ("Button", "content"): "Text or control displayed on the button.",
    ("ListItem", "content"): "Main displayed content of the list item.",
}


def describe(owner: str, parameter: str) -> str:
    if (owner, parameter) in OVERRIDES:
        return OVERRIDES[owner, parameter]
    if parameter in EVENTS:
        return EVENTS[parameter]
    if parameter.startswith("animate_"):
        property_name = parameter.removeprefix("animate_")
        return f"Animation settings applied when {property_name} changes."
    return DESCRIPTIONS[parameter]
