"""Plain-language explanations for Saturn constructor parameters."""

DESCRIPTIONS = {
    "shift": "Whether the Shift modifier was pressed for this event.",
    "ctrl": "Whether the Control modifier was pressed for this event.",
    "alt": "Whether the Alt modifier was pressed for this event.",
    "meta": "Whether the platform Meta modifier was pressed for this event.",
    "brightness": "Current system or native title-bar brightness: light or dark.",
    "type": "The kind of native window event.",
    # Layout, presentation, and shared control state.
    "align": "Alignment of the control within the available area.",
    "alignment": "Alignment of child content within a container or layout.",
    "bottom": "Distance from the bottom edge of a Stack.",
    "color": "Color of foreground content, text, or drawing.",
    "content": "Text or child control to display.",
    "controls": "Child controls in display order.",
    "data": "Custom data attached to the control or event.",
    "disabled": "Disable interaction and use the disabled appearance when True.",
    "expand": "Fill remaining parent space; a number sets the flex ratio.",
    "height": "Specified control height.",
    "horizontal_alignment": "Alignment on the horizontal or cross axis.",
    "items": "Items passed to a layout, group, or menu.",
    "left": "Distance from the left edge of a Stack.",
    "margin": "Space outside the control.",
    "offset": "Displacement applied beyond the layout position.",
    "opacity": "Control opacity, from 0 (transparent) to 1 (opaque).",
    "padding": "Space around the control's content.",
    "right": "Distance from the right edge of a Stack.",
    "rotate": "Rotation applied when drawing the control.",
    "scale": "Scale applied when drawing the control.",
    "spacing": "Space between adjacent child controls.",
    "item_extent": "Fixed item height, or width for a horizontal list; enables lazy layout.",
    "tight": "Size the layout closely to its children when True.",
    "top": "Distance from the top edge of a Stack.",
    "vertical_alignment": "Alignment on the vertical or cross axis.",
    "visible": "Hide the control when False.",
    "width": "Specified control width.",
    "x": "Horizontal coordinate or displacement.",
    "y": "Vertical coordinate or displacement.",
    "bgcolor": "Background color of the control or container.",
    "border": "Border settings.",
    "border_color": "Border color of the input area.",
    "border_radius": "Corner radius of the border or background.",
    "gradient": "Gradient used to fill the background.",
    "shadow": "Shadow outside the control.",
    "ink": "Whether to draw ripple feedback on clicks.",
    "elevation": "Surface elevation, which determines shadow strength.",
    "variant": "Visual variant of this control.",
    "horizontal": "Use horizontal scrolling or layout when True.",
    "vertical": "Use vertical layout when True.",
    "auto_scroll": "Scroll to the end automatically as content is added.",
    "leading": "Control or area before the main content.",
    "trailing": "Control or area after the main content.",
    "leading_indent": "Inset at the start of a divider.",
    "trailing_indent": "Inset at the end of a divider.",
    "thickness": "Thickness of a line or divider.",
    "fit": "How an image scales and crops within its bounds.",
    "src": "Image source: a local path, bytes, or data URI.",
    # Text, icons, and input.
    "value": "Current value of the control or data object.",
    "values": "Set of initial values.",
    "text": "Text displayed on the control.",
    "size": "Size of the text, icon, or control.",
    "weight": "Text font weight.",
    "italic": "Whether to use italic text.",
    "text_align": "Text alignment within the available width.",
    "max_lines": "Maximum number of lines to show or accept.",
    "no_wrap": "Prevent automatic line wrapping when True.",
    "selectable": "Whether text can be selected with the pointer.",
    "font_family": "Font family name registered on the page.",
    "letter_spacing": "Extra space between characters.",
    "overflow": "How to handle text beyond the available space.",
    "decoration": "Text or border decoration settings.",
    "icon": "Icon to draw.",
    "icon_color": "Foreground color of the icon.",
    "icon_size": "Displayed icon size.",
    "selected_icon": "Alternate icon shown when selected.",
    "label": "Label beside an input, option, or control.",
    "hint_text": "Hint shown before a value is entered or selected.",
    "text_size": "Font size of entered or selected text.",
    "text_style": "Style of entered or displayed text.",
    "password": "Mask entered characters when True.",
    "can_reveal_password": "Show a button for toggling password visibility.",
    "multiline": "Allow multiple lines of text input.",
    "read_only": "Display content without allowing edits when True.",
    "filled": "Use a filled input area.",
    "fill_color": "Background color of a filled input area.",
    "cursor_color": "Color of the text insertion cursor.",
    "options": "Options available in the dropdown menu.",
    "checked": "Whether the toggle button is currently selected.",
    "selected": "Whether the list item or icon button is selected.",
    "active_color": "Color used in the selected or on state.",
    "inactive_color": "Color used in the unselected state.",
    "thumb_color": "Color of the slider thumb.",
    "label_position": "Position of the label relative to the selection control.",
    "min": "Lower bound of the selectable range.",
    "max": "Upper bound of the selectable range.",
    "divisions": "Number of discrete steps in the range.",
    "round": "Number of decimal places in the displayed value.",
    "hover_color": "Color used in the hover state.",
    "mouse_cursor": "Pointer style shown on hover.",
    "drag_interval": "Minimum interval between consecutive drag events.",
    "hover_interval": "Minimum interval between consecutive hover events.",
    # Buttons, feedback, and animation.
    "autofocus": "Try to focus this control when the page opens.",
    "url": "Destination opened when the button is clicked.",
    "expressive": "Enable Expressive sizing and shape behavior.",
    "shape": "Base shape of the button.",
    "style": "Additional button style settings.",
    "connected": "Arrange buttons as a connected group.",
    "container_color": "Background color of a list item or container in its normal state.",
    "content_color": "Foreground color of list item content in its normal state.",
    "expanded_ratio": "Fraction by which a pressed button can grow in width.",
    "compression_limit": "Minimum size to which neighboring buttons can shrink.",
    "trailing_icon": "Icon in the secondary action area of a split button.",
    "headline": "Primary title of a list item.",
    "overline": "Small text above a list item's title.",
    "supporting": "Supporting text below a list item's title.",
    "selected_container_color": "List item background color when selected.",
    "selected_content_color": "List item foreground color when selected.",
    "expanded": "Whether the floating component or menu is expanded.",
    "vibrant": "Use a more vivid surface color for the toolbar.",
    "contained": "Place the loading indicator on a container background.",
    "bar_height": "Thickness of the linear progress bar.",
    "stroke_width": "Width of a progress ring or wave stroke.",
    "amplitude": "Height of the wave relative to its baseline.",
    "wavelength": "Distance between adjacent wave peaks.",
    "wave_speed": "Movement speed of the wave animation.",
    "title": "Title of a dialog, notification, or window.",
    "tooltip": "Short hint shown on hover.",
    "actions": "Action buttons at the bottom of a dialog.",
    "action": "Single action label or button on a snackbar.",
    "modal": "Prevent closing the dialog by clicking its barrier when True.",
    "open": "Whether the dialog or snackbar is open.",
    "duration": "Duration; the unit depends on the relevant class.",
    "animate": "Animation settings applied when a property changes.",
    "curve": "Curve used for animation interpolation.",
    "show_duration": "Duration of the entrance transition.",
    "exit_duration": "Duration of the exit transition.",
    "wait_duration": "Delay before the next display.",
    # Theme and geometry value objects.
    "color_scheme_seed": "Seed color used to generate the theme palette.",
    "bottom_left": "Corner radius at the bottom left.",
    "bottom_right": "Corner radius at the bottom right.",
    "top_left": "Corner radius at the top left.",
    "top_right": "Corner radius at the top right.",
    "angle": "Rotation angle.",
    "scale_x": "Horizontal scale factor.",
    "scale_y": "Vertical scale factor.",
    "blur_radius": "Shadow blur radius.",
    "spread_radius": "Distance the shadow outline expands outward.",
    "side": "Settings for one border side.",
    "origin": "Reference origin for the transformation.",
    "filter_quality": "Sampling quality used when scaling an image.",
    "gap_padding": "Space on either side of a floating label's border gap.",
    "size_constraints": "Allowed minimum and maximum dimensions.",
    "vertical_offset": "Additional vertical displacement.",
    "prefer_below": "Place the tooltip below the control when space permits.",
    "tap_to_dismiss": "Dismiss the tooltip when its area is tapped.",
    "trigger_mode": "Interaction that triggers the tooltip.",
    "enable_feedback": "Provide interaction feedback when enabled.",
    "exclude_from_semantics": "Exclude this control from accessibility semantics.",
    "transform_hit_tests": "Apply the geometry transform to the hit area as well.",
    "days": "Days in the duration.",
    "hours": "Hours in the duration.",
    "minutes": "Minutes in the duration.",
    "seconds": "Seconds in the duration.",
    "milliseconds": "Milliseconds in the duration.",
    "microseconds": "Microseconds in the duration.",
    # App, events, and file picker data.
    "app": "Current application instance supplied by the runtime.",
    "main": "Application entry point that receives a Page.",
    "backend": "Rendering backend to use. For saturn.run(), omission selects OpenGL unless SATURN_BACKEND overrides it.",
    "control": "Control that produced the event or holds the data.",
    "error": "Error message when an operation fails.",
    "message": "Text of the event or result message.",
    "method": "Name of the method that triggered the operation.",
    "name": "Name of the object, file, or resource.",
    "path": "Local file or directory path.",
    "file_name": "Suggested name for a saved file.",
    "bytes": "Byte content of the file or resource.",
    "files": "Files selected, uploaded, or returned.",
    "id": "Identifier of the file or object.",
    "key": "Key used to locate a control or service.",
    "ref": "Place to store a control or service reference.",
    "progress": "Completion progress of an upload or operation.",
    "upload_url": "Destination URL for file uploads.",
    # Constructor pass-through parameters.
    "args": "Positional arguments passed to the parent constructor.",
    "kwargs": "Keyword arguments passed to the parent constructor.",
    "base": "Keyword arguments passed to Control, such as width and height.",
    "foreground_color": "Foreground color of the floating action button.",
    "max_length": "Maximum text length; None or -1 leaves it unlimited.",
    "mini": "Use the small floating action button size.",
    "obscuring_character": "Single character used to mask password text.",
    "shift_enter": "Require Shift+Enter to insert a newline in a multiline field.",
    "show_cursor": "Whether to display the input caret.",
    "_ignored": "Additional control arguments currently accepted without behavior.",
}

EVENTS = {
    "on_action": "Callback called when the snackbar action is clicked.",
    "on_animation_end": "Callback called when the control animation finishes.",
    "on_blur": "Callback called when the control loses focus.",
    "on_change": "Callback called when the value changes.",
    "on_change_start": "Callback called when dragging or value editing begins.",
    "on_change_end": "Callback called when dragging or value editing ends.",
    "on_click": "Callback called when the control is clicked.",
    "on_dismiss": "Callback called when the dialog or snackbar closes.",
    "on_enter": "Callback called when the pointer enters the control.",
    "on_exit": "Callback called when the pointer leaves the control.",
    "on_focus": "Callback called when the control gains focus.",
    "on_hover": "Callback called when the pointer's hover state changes.",
    "on_long_press": "Callback called when the control is long pressed.",
    "on_result": "Callback called when a file selection or save returns a result.",
    "on_scroll": "Callback called when the list scrolls.",
    "on_select": "Callback called when a menu item or option is selected.",
    "on_submit": "Callback called when input is submitted.",
    "on_tap": "Callback called when a tap completes.",
    "on_tap_down": "Callback called when a press begins.",
    "on_trailing_click": "Callback called when the split button's secondary action is clicked.",
    "on_upload": "Callback called when file upload status changes.",
}

OVERRIDES = {
    ("KeyboardEvent", "key"): "Pressed key name, such as S, Enter, or Arrow Left.",
    ("KeyboardEvent", "name"): "Event name: keyboard_event.",
    ("PageResizeEvent", "name"): "Event name: resize.",
    ("PageResizeEvent", "width"): "Logical client width after resizing.",
    ("PageResizeEvent", "height"): "Logical client height after resizing.",
    ("PlatformBrightnessChangeEvent", "name"): "Event name: platform_brightness_change.",
    ("run", "title"): "Application window title.",
    ("Text", "value"): "Text content to display.",
    ("TextField", "value"): "Initial or current text field content.",
    ("Checkbox", "value"): "Whether the checkbox is checked.",
    ("Slider", "value"): "Current slider value.",
    ("ProgressBar", "value"): "Progress, usually from 0 to 1; None means indeterminate.",
    ("ProgressRing", "value"): "Progress, usually from 0 to 1; None means indeterminate.",
    ("Dropdown", "value"): "Key of the currently selected option.",
    ("Image", "color"): "Optional image tint multiplied with the source pixels.",
    ("SnackBar", "duration"): "How many milliseconds the snackbar remains visible.",
    ("Container", "alignment"): "Alignment of content inside the container.",
    ("Row", "alignment"): "Arrangement of children along the horizontal main axis.",
    ("Column", "alignment"): "Arrangement of children along the vertical main axis.",
    ("Button", "content"): "Text or control displayed on the button.",
    ("ListItem", "content"): "Main displayed content of the list item.",
}


DESCRIPTIONS.update({
    "unsupported": "Unknown keyword arguments raise TypeError.",
    "key": "Application key identifying the control or option.",
    "ref": "Ref whose current property receives this control.",
    "rtl": "Right-to-left direction; None inherits the parent's direction.",
    "aspect_ratio": "Positive width-to-height ratio fitted within parent constraints.",
    "can_request_focus": "Allow programmatic and keyboard focus when True.",
    "mouse_cursor": "Cursor displayed while hovering over the control.",
    "semantics_label": "Accessibility description metadata; native accessibility is not implemented.",
    "semantics_value": "Accessibility value metadata.",
    "size_change_interval": "Minimum interval in milliseconds between size events; the final size is delivered.",
    "route": "Application route string shared by its native windows.",
    "view": "Subpage removed from the navigation stack.",
    "appbar": "Optional custom Subpage header control.",
    "scroll": "Scroll mode: auto, always, hidden, or none.",
    "scroll_interval": "Minimum interval in milliseconds between scroll events.",
    "effect": "GPU effect: gradient, noise, ripple, or plasma.",
    "uniforms": "Built-in effect parameters or custom GLSL scalar/vector uniform values.",
    "shader": "ShaderEffect, GLSL source string, or pathlib.Path to a fragment source file.",
    "includes": "Mapping from include names to GLSL snippets.",
    "include_dirs": "Explicit folders searched for GLSL include files.",
    "parent": "Page owning this native child window.",
    "anchor": "Placement relative to the owner: center, sides, corners, or Alignment.",
    "follow_parent": "Keep the child at its relative attachment position when windows move or resize.",
    "expand_loose": "Treat the flex share as a maximum instead of forcing the child to fill it.",
    "speed": "Multiplier for elapsed Shader animation time.",
    "time": "Shader time offset in seconds.",
    "fallback_color": "Static fill used by the software backend.",
    "begin": "Gradient start Alignment.", "end": "Gradient end Alignment.",
    "colors": "Ordered colors along the gradient.",
    "stops": "Optional ascending normalized positions of gradient colors.",
    "clip_behavior": "Clip mode; GPU rotated clips use conservative axis-aligned bounds.",
    "wrap": "Wrap children into more runs when available space is insufficient.",
    "run_alignment": "Distribution of wrapped runs across the cross axis.",
    "run_spacing": "Gap between wrapped runs.",
    "intrinsic_width": "Fit Stack width to its content.",
    "intrinsic_height": "Fit Stack height to its content.",
    "repeat": "Image tiling direction: none, both axes, horizontal, or vertical.",
    "cache_width": "Requested image cache target width.",
    "cache_height": "Requested image cache target height.",
    "cache_extent": "ListView preload distance in logical pixels.",
    "build_controls_on_demand": "Place known-height list children lazily while retaining control objects.",
    "first_item_prototype": "Use the first child's measured extent for all rows.",
    "prototype_item": "Control providing the measured extent of every row.",
    "reverse": "Reverse list layout direction.",
    "divider_thickness": "Thickness of list separators.",
    "semantic_child_count": "Declared accessibility child count metadata.",
    "semantic_container": "Accessibility container metadata.",
    "selection": "TextSelection holding the selected character endpoints.",
    "base_offset": "Starting character offset of a selection.",
    "extent_offset": "Ending character offset of a selection.",
    "affinity": "Selection affinity at a line boundary.",
    "directional": "Whether selection direction is significant.",
    "capitalization": "Capitalization applied to inserted text.",
    "input_filter": "Regex InputFilter applied to inserted text.",
    "regex_string": "Pattern matching text to accept or reject.",
    "allow": "Accept matching text when True; reject it when False.",
    "replacement_string": "Replacement for rejected filter matches.",
    "enable_interactive_selection": "Allow pointer/keyboard selection and copy.",
    "show_selection_cursor": "Draw a caret for focused selectable Text.",
    "text_vertical_align": "Vertical placement of TextField content.",
    "min_lines": "Minimum visible lines of multiline input.",
    "font_family_fallback": "Ordered additional families for missing glyphs.",
    "helper": "Control below the input providing helper content.",
    "counter": "Control beside input helper/error content.",
    "prefix": "Control before the editable input text.",
    "suffix": "Control after the editable input text.",
    "selected_suffix": "Control displayed after the selected dropdown option.",
    "editable": "Allow typing in the dropdown's selection field.",
    "enable_filter": "Filter dropdown options by entered text.",
    "enable_search": "Search options while editing the dropdown.",
    "menu_height": "Maximum height of the bounded dropdown menu.",
    "menu_width": "Width of the dropdown menu.",
    "interaction": "Slider tap/drag interaction mode.",
    "secondary_track_value": "Value reached by the Slider secondary track.",
    "tristate": "Allow Checkbox values True, False, and None.",
    "toggleable": "Allow a selected Radio to become unselected.",
    "animation_duration": "Supported style transition duration in milliseconds.",
    "visual_density": "Compact, comfortable, or standard control sizing where supported.",
    "ignore_pointers": "Exclude the Container subtree from pointer hit testing.",
    "ignore_interactions": "Disable Slider interaction without changing appearance.",
    "allowed_devices": "Pointer device restrictions; non-default requests are unsupported.",
    "behavior": "Gesture hit-test behavior.",
    "persist": "Keep the SnackBar open until explicitly dismissed.",
    "show_close_icon": "Show a clickable SnackBar close icon.",
    "action_overflow_threshold": "Width fraction at which the SnackBar action wraps.",
    "track_gap": "Gap between a progress stroke and its track.",
    "stop_indicator_radius": "Radius of the progress end marker.",
    "stroke_align": "Alignment of the progress stroke relative to its bounds.",
    "stroke_cap": "Shape of stroke endpoints.",
    "gapless_playback": "Keep the previous image while a replacement is unavailable.",
    "apply_text_scaling": "Apply supported text/icon scaling.",
    "anti_alias": "Request smooth image edges on the active backend.",
    "dense": "Use compact input decoration.",
    "collapsed": "Remove ordinary input decoration spacing.",
    "theme": "Light theme configuration.", "dark_theme": "Dark theme configuration.",
    "theme_mode": "Light, dark, or detected system preference.",
    "placeholder_src": "Image shown while the requested source is unavailable.",
    "placeholder_fit": "BoxFit used for placeholder content.",
    "error_content": "Control shown when an image cannot be decoded.",
    "radius": "Corner radius of a shape border.",
    "min_width": "Minimum width.", "max_width": "Maximum width.",
    "min_height": "Minimum height.", "max_height": "Maximum height.",
    "scrollable": "Scroll overflowing dialog content inside the dialog.",
    "border_width": "Input outline thickness.",
    "focused_border_width": "Input outline thickness while focused.",
    "cursor_width": "Input caret width.", "cursor_height": "Input caret height.",
    "cursor_radius": "Input caret corner radius.",
    "selection_cursor_width": "Selectable Text caret width.",
    "selection_cursor_height": "Selectable Text caret height.",
    "track_outline_width": "Switch track outline thickness.",
    "splash_radius": "Pointer feedback radius limit.",
    "border_side": "Outline color and thickness as a BorderSide.",
    "actions_alignment": "Main-axis arrangement of dialog action controls.",
    "actions_overflow_button_spacing": "Spacing between wrapped dialog actions.",
    "ignore_up_down_keys": "Allow Up/Down keys to reach the application rather than moving the caret.",
    "word_spacing": "Extra spacing between words; nonzero requests are unsupported.",
    "decoration_thickness": "Text decoration thickness; non-default requests are unsupported.",
})

OVERRIDES.update({
    ("Subpage", "modal"): "Block the owning native window's input until this child closes.",
    ("Shader", "animate"): "Request frames to advance time while visible on a GPU backend.",
    ("Shader", "effect"): "Compatibility alias for shader; pass only one of them.",
    ("Shader", "buffer"): "Optional ShaderBuffer rendered on the GPU before the final fragment; sample with saturnSampleBuffer(uv).",
    ("ShaderBuffer", "vertex_shader"): "GLSL vertex source string or pathlib.Path; defines void main() and portable SATURN vertex/instance identifiers.",
    ("ShaderBuffer", "fragment_shader"): "GLSL fragment source string or pathlib.Path; defines void main() and returns premultiplied RGBA.",
    ("ShaderBuffer", "instances"): "Number of six-vertex instances, from 1 to 1,000,000.",
})
for _name in ("autocorrect autofill_hints enable_suggestions enable_ime_personalized_learning "
              "enable_stylus_handwriting keyboard_brightness keyboard_type smart_dashes_type smart_quotes_type "
              "spans theme_style fill grade optical_size color_filter blend_mode color_blend_mode blur "
              "foreground_decoration image shadows show_border_on_foreground year_2023 menu_style expanded_insets "
              "auto_scroll_animation fade_in_animation placeholder_fade_out_animation multi_tap_touches "
              "trackpad_scroll_causes_scale dismiss_direction").split():
    DESCRIPTIONS.setdefault(_name, f"Requested {_name.replace('_', ' ')} option; see the control comparison for supported values and restrictions.")


def describe(owner: str, parameter: str) -> str:
    if (owner, parameter) in OVERRIDES:
        return OVERRIDES[owner, parameter]
    if parameter in EVENTS:
        return EVENTS[parameter]
    if parameter.startswith("animate_"):
        property_name = parameter.removeprefix("animate_")
        return f"Animation settings applied when {property_name} changes."
    if parameter in DESCRIPTIONS:
        return DESCRIPTIONS[parameter]
    if parameter.startswith("on_"):
        return f"Callback for {parameter[3:].replace('_', ' ')}; accepts zero arguments or an event."
    for suffix, text in (("_bgcolor", "Background color for"), ("_color", "Color for"), ("_padding", "Insets around"),
                         ("_style", "Style applied to"), ("_icon", "Icon used for"),
                         ("_elevation", "Shadow elevation during"), ("_text", "Text displayed as")):
        if parameter.endswith(suffix):
            return f"{text} {parameter[:-len(suffix)].replace('_', ' ')}."
    return DESCRIPTIONS[parameter]
