"""Plain-language explanations for Saturn constructor parameters."""

DESCRIPTIONS = {
    # Layout, presentation and shared control state.
    "align": "控件在可用区域内的对齐位置。",
    "alignment": "子内容在容器或布局中的排列方式。",
    "bottom": "相对 Stack 底边的定位距离。",
    "color": "前景、文字或绘制内容的颜色。",
    "content": "要显示的文本或子控件。",
    "controls": "按顺序排列的子控件列表。",
    "data": "附着在控件或事件上的自定义数据。",
    "disabled": "为 True 时禁用交互，并使用禁用状态外观。",
    "expand": "占用父布局中的剩余空间；数字可作为伸缩比例。",
    "height": "控件的指定高度。",
    "horizontal_alignment": "横向或交叉轴上的对齐方式。",
    "items": "传给布局、分组或菜单的项目列表。",
    "left": "相对 Stack 左边的定位距离。",
    "margin": "控件外侧的留白。",
    "offset": "在布局位置之外施加的位移。",
    "opacity": "控件透明度；0 为透明，1 为不透明。",
    "padding": "控件内容四周的内边距。",
    "right": "相对 Stack 右边的定位距离。",
    "rotate": "绘制控件时使用的旋转值。",
    "scale": "绘制控件时使用的缩放值。",
    "spacing": "相邻子控件之间的间距。",
    "tight": "使布局尽量贴合子控件的实际尺寸。",
    "top": "相对 Stack 上边的定位距离。",
    "vertical_alignment": "纵向或交叉轴上的对齐方式。",
    "visible": "为 False 时不显示控件。",
    "width": "控件的指定宽度。",
    "x": "水平坐标或位移分量。",
    "y": "垂直坐标或位移分量。",
    "bgcolor": "控件或容器的背景颜色。",
    "border": "边框配置。",
    "border_color": "输入区域的边框颜色。",
    "border_radius": "边框或背景的圆角半径。",
    "gradient": "用于填充背景的渐变。",
    "shadow": "控件外侧的阴影设置。",
    "ink": "是否绘制点击反馈的水波纹。",
    "elevation": "表面高度，对应阴影的视觉强度。",
    "variant": "选择该控件的视觉变体。",
    "horizontal": "为 True 时采用水平滚动或水平排布。",
    "vertical": "为 True 时采用竖向布局。",
    "auto_scroll": "内容增加时是否自动滚动到末尾。",
    "leading": "放在主要内容前面的控件或区域。",
    "trailing": "放在主要内容后面的控件或区域。",
    "leading_indent": "分隔线起点留白。",
    "trailing_indent": "分隔线终点留白。",
    "thickness": "线条或分隔线的粗细。",
    "fit": "图片在给定尺寸内的缩放和裁切方式。",
    "src": "图片来源，可为本地路径、字节数据或 data URI。",
    # Text, icons and input.
    "value": "控件或数据对象的当前值。",
    "values": "传入的一组初始值。",
    "text": "显示在控件上的文字。",
    "size": "文字、图标或控件的尺寸等级。",
    "weight": "文本字重。",
    "italic": "是否使用斜体。",
    "text_align": "文本在可用宽度内的对齐方式。",
    "max_lines": "最多显示或输入的行数。",
    "no_wrap": "为 True 时不自动换行。",
    "selectable": "文本是否可被鼠标选中。",
    "font_family": "使用页面注册的字体名称。",
    "letter_spacing": "字符之间额外增加的间距。",
    "overflow": "文本超出可用区域时的处理方式。",
    "decoration": "文本装饰或边框装饰设置。",
    "icon": "要绘制的图标。",
    "icon_color": "图标的前景颜色。",
    "icon_size": "图标的显示大小。",
    "selected_icon": "选中状态下显示的替代图标。",
    "label": "显示在输入框、选项或控件旁的标签。",
    "hint_text": "尚无输入或选择时显示的提示文字。",
    "text_size": "输入或选择内容的文字大小。",
    "text_style": "输入或显示文字的样式。",
    "password": "为 True 时遮蔽输入字符。",
    "can_reveal_password": "是否提供显示密码的切换按钮。",
    "multiline": "是否允许输入多行文本。",
    "read_only": "为 True 时显示内容但不允许编辑。",
    "filled": "是否使用填充式输入区域。",
    "fill_color": "填充式输入区域的背景颜色。",
    "cursor_color": "文本插入光标的颜色。",
    "options": "下拉菜单中的可选项。",
    "checked": "切换按钮当前是否处于选中状态。",
    "selected": "列表项或图标按钮当前是否选中。",
    "active_color": "选中或开启状态使用的颜色。",
    "inactive_color": "未选中状态的颜色。",
    "thumb_color": "滑块圆点的颜色。",
    "label_position": "标签相对于选择控件的位置。",
    "min": "可选择数值的下界。",
    "max": "可选择数值的上界。",
    "divisions": "把范围划分为多少个离散步进。",
    "round": "数值标签或输出保留的小数位数。",
    "hover_color": "悬停状态使用的颜色。",
    "mouse_cursor": "悬停时显示的鼠标指针样式。",
    "drag_interval": "连续拖动事件的最短触发间隔。",
    "hover_interval": "连续悬停事件的最短触发间隔。",
    # Buttons, feedback and animation.
    "autofocus": "页面打开时是否尝试自动获得焦点。",
    "url": "点击按钮时打开的目标地址。",
    "expressive": "是否启用 Expressive 尺寸与形状行为。",
    "shape": "按钮的基础形状。",
    "style": "附加的按钮样式配置。",
    "connected": "按钮组中的按钮是否采用连接式排列。",
    "container_color": "列表项或容器在普通状态下的背景色。",
    "content_color": "列表项内容在普通状态下的前景色。",
    "expanded_ratio": "按钮按压时可增加的宽度比例。",
    "compression_limit": "相邻按钮可压缩的最小尺寸限制。",
    "trailing_icon": "分段按钮副操作区域的图标。",
    "headline": "列表项中最醒目的主标题。",
    "overline": "列表项标题上方的小字。",
    "supporting": "列表项标题下方的辅助说明。",
    "selected_container_color": "列表项选中时的背景色。",
    "selected_content_color": "列表项选中时的前景色。",
    "expanded": "浮动组件或菜单当前是否展开。",
    "vibrant": "工具栏是否采用更鲜明的表面配色。",
    "contained": "加载指示器是否放在容器背景中。",
    "bar_height": "线性进度条的厚度。",
    "stroke_width": "进度环或波形线条的宽度。",
    "amplitude": "波浪相对基线的起伏高度。",
    "wavelength": "波形相邻峰值之间的距离。",
    "wave_speed": "波形动画的移动速度。",
    "title": "对话框、提示或窗口的标题。",
    "tooltip": "鼠标悬停时显示的简短提示。",
    "actions": "对话框底部的操作按钮列表。",
    "action": "提示条上的单个操作文本或按钮。",
    "modal": "为 True 时禁止点击遮罩关闭对话框。",
    "open": "对话框或提示条当前是否处于打开状态。",
    "duration": "持续时间；具体单位由相应类定义。",
    "animate": "属性变化时采用的动画配置。",
    "curve": "动画插值使用的曲线。",
    "show_duration": "显示过渡所需时间。",
    "exit_duration": "消失过渡所需时间。",
    "wait_duration": "进入下一次显示前的等待时间。",
    # Theme and geometry value objects.
    "color_scheme_seed": "生成主题配色的种子颜色。",
    "bottom_left": "左下角的圆角大小。",
    "bottom_right": "右下角的圆角大小。",
    "top_left": "左上角的圆角大小。",
    "top_right": "右上角的圆角大小。",
    "angle": "旋转角度。",
    "scale_x": "水平方向的缩放比例。",
    "scale_y": "垂直方向的缩放比例。",
    "blur_radius": "阴影模糊半径。",
    "spread_radius": "阴影轮廓向外扩张的距离。",
    "side": "单条边框线的配置。",
    "origin": "变换的参考原点。",
    "filter_quality": "图片缩放时使用的采样质量。",
    "gap_padding": "输入框浮动标签两侧的缺口留白。",
    "size_constraints": "尺寸允许的最小值与最大值范围。",
    "vertical_offset": "垂直方向额外偏移的距离。",
    "prefer_below": "空间允许时优先把提示显示在控件下方。",
    "tap_to_dismiss": "点击提示区域时是否关闭提示。",
    "trigger_mode": "触发提示出现的交互方式。",
    "enable_feedback": "交互时是否提供反馈效果。",
    "exclude_from_semantics": "是否从辅助功能语义树中排除。",
    "transform_hit_tests": "几何变换是否同步影响点击命中区域。",
    "days": "时间值中的天数。",
    "hours": "时间值中的小时数。",
    "minutes": "时间值中的分钟数。",
    "seconds": "时间值中的秒数。",
    "milliseconds": "时间值中的毫秒数。",
    "microseconds": "时间值中的微秒数。",
    # App, events and file-picker data.
    "app": "当前应用实例，由运行时传入。",
    "main": "应用入口函数，接收 Page 对象。",
    "backend": "绘制后端的选择。",
    "control": "产生事件或关联数据的控件。",
    "error": "操作失败时的错误信息。",
    "message": "事件或结果的文字消息。",
    "method": "触发操作的方法名称。",
    "name": "对象、文件或资源的名称。",
    "path": "本地文件或目录路径。",
    "file_name": "保存时建议使用的文件名。",
    "bytes": "文件或资源的字节内容。",
    "files": "选择、上传或返回的文件列表。",
    "id": "文件或对象的标识值。",
    "key": "用于定位控件或服务的键。",
    "ref": "保存控件或服务引用的位置。",
    "progress": "上传或操作的完成进度。",
    "upload_url": "文件上传的目标地址。",
    # Constructor pass-through parameters.
    "args": "传给父类构造函数的位置参数。",
    "kwargs": "传给父类构造函数的关键字参数。",
    "base": "传给基础 Control 构造函数的关键字参数，例如 width、height。",
    "_flet_ignored": "为兼容 Flet 风格调用而接收的额外参数；当前不会自动产生功能。",
}

EVENTS = {
    "on_action": "点击提示条操作时调用的回调。",
    "on_animation_end": "控件动画完成时调用的回调。",
    "on_blur": "控件失去焦点时调用的回调。",
    "on_change": "值改变时调用的回调。",
    "on_change_start": "开始拖动或修改数值时调用的回调。",
    "on_change_end": "结束拖动或修改数值时调用的回调。",
    "on_click": "点击控件时调用的回调。",
    "on_dismiss": "对话框或提示条关闭时调用的回调。",
    "on_enter": "指针进入控件区域时调用的回调。",
    "on_exit": "指针离开控件区域时调用的回调。",
    "on_focus": "控件获得焦点时调用的回调。",
    "on_hover": "指针悬停状态变化时调用的回调。",
    "on_long_press": "长按控件时调用的回调。",
    "on_result": "文件选择或保存操作返回结果时调用的回调。",
    "on_scroll": "列表滚动时调用的回调。",
    "on_select": "选中菜单项或选项时调用的回调。",
    "on_submit": "提交输入内容时调用的回调。",
    "on_tap": "完成轻触操作时调用的回调。",
    "on_tap_down": "开始按下控件时调用的回调。",
    "on_trailing_click": "点击分段按钮副操作区域时调用的回调。",
    "on_upload": "文件上传状态变化时调用的回调。",
}

OVERRIDES = {
    ("run", "width"): "应用窗口的初始宽度，单位为像素。",
    ("run", "height"): "应用窗口的初始高度，单位为像素。",
    ("run", "title"): "应用窗口标题。",
    ("Text", "value"): "要显示的文本内容。",
    ("TextField", "value"): "文本框初始或当前输入内容。",
    ("Checkbox", "value"): "复选框当前是否勾选。",
    ("Slider", "value"): "滑块当前选中的数值。",
    ("ProgressBar", "value"): "进度值，通常在 0 到 1 之间；None 表示不确定进度。",
    ("ProgressRing", "value"): "进度值，通常在 0 到 1 之间；None 表示不确定进度。",
    ("Dropdown", "value"): "当前选中选项的键。",
    ("Image", "color"): "可选的图片着色颜色，会与原像素相乘。",
    ("SnackBar", "duration"): "提示条显示的毫秒数。",
    ("Container", "alignment"): "内容在容器内部的对齐位置。",
    ("Row", "alignment"): "子控件沿水平主轴的排列方式。",
    ("Column", "alignment"): "子控件沿垂直主轴的排列方式。",
    ("Button", "content"): "按钮上显示的文字或控件。",
    ("ListItem", "content"): "列表项的主要显示内容。",
}


def describe(owner: str, parameter: str) -> str:
    if (owner, parameter) in OVERRIDES:
        return OVERRIDES[owner, parameter]
    if parameter in EVENTS:
        return EVENTS[parameter]
    if parameter.startswith("animate_"):
        property_name = parameter.removeprefix("animate_")
        return f"{property_name} 属性变化时的动画配置。"
    return DESCRIPTIONS[parameter]
