"""Reproduce the GLSL Orb assets from an upstream Orb checkout (MIT).

Uses upstream's typed Metal export to preserve the WGSL calculations without
implementing a runtime WGSL compiler. No upstream executable is run.
"""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
LABELS = [("siri", "Siri Wave", 9), ("voiceWave", "Voice Membrane", 19),
          ("particleRibbon", "Particle Ribbons", 24), ("blueDrop", "Crystal Drop", 20),
          ("violetEmber", "Violet Ember", 21), ("refractiveBlob", "Refractive Gel", 23),
          ("chromaticMetal", "Chromatic Metal", 22), ("aurora", "Aurora Veil", 10),
          ("frost", "Frost Flow", 15), ("chrome", "Liquid Chrome", 12),
          ("opal", "Iridescent Opal", 13), ("spectrum", "Prismatic Field", 14),
          ("plasma", "Neural Plasma", 11)]
NOTICE = "// Adapted from Orb, https://github.com/LerSent001/orb\n// Copyright (c) 2026 LerSent001. MIT License: ORB-LICENSE.txt.\n// Generated by tools/port_orb_shaders.py; edit the converter to regenerate.\n"


def convert(text):
    text = re.sub(r'char _pad\d+\[\d+\];', '', text)
    text = re.sub(r'constant Uniforms&', 'Uniforms', text)
    text = text.replace('constant ', 'const ').replace('metal::', '')
    for n in (2, 3, 4):
        text = re.sub(r'\bfloat'+str(n)+r'\b', 'vec'+str(n), text)
        text = re.sub(r'\buint'+str(n)+r'\b', 'uvec'+str(n), text)
    text = re.sub(r'as_type<(vec[234]|float)>\(', 'uintBitsToFloat(', text)
    text = re.sub(r'as_type<(int|uint)>\(', r'\1(', text)
    text = re.sub(r'all\((loop_bound\w*) == (uvec2\([^)]*\))\)', r'all(equal(\1, \2))', text)
    text = re.sub(r'static_cast<(float|int|uint)>\(', r'\1(', text)
    text = text.replace('atan2(', 'atan(')
    text = re.sub(r'\bactive\b', 'particleActive', text)
    text = re.sub(r'const uint (\w+) = (\d+);', r'const uint \1 = \2u;', text)
    text = re.sub(r'(vec[234]|float) (\w+) = \{\};', r'\1 \2 = \1(0);', text)
    text = re.sub(r'MfRamp \{([^{}]*), \{\}, ([^{}]*)\}', r'MfRamp(\1, \2)', text)
    return text


def generate(source):
    output = ROOT / '.static/shaders'
    metal = (source / 'effect.metal').read_text(encoding='utf-8')
    uniform_struct = convert(re.search(r'struct Uniforms \{.*?\};', metal, re.S)[0])
    fields = re.findall(r'(vec[234]|float) (\w+);', uniform_struct)
    declarations = '\n'.join(f'uniform {kind} orb_{name.rstrip("_")};'
                              for kind, name in fields if name not in ('size', 'time'))
    args = ["u_resolution" if name == 'size' else "u_time" if name == 'time'
            else 'orb_'+name.rstrip('_') for _, name in fields]
    common = NOTICE + declarations + '\n' + uniform_struct
    common += '\nUniforms orbUniforms() { return Uniforms('+', '.join(args)+'); }\n'
    helpers = convert(metal[metal.index('struct MfRamp'):metal.index('struct VOut')])
    helpers += convert(metal[metal.index('constant float GL_FU'):metal.index('struct vs_mainInput')])
    liquid = common + helpers
    (output / 'orb-liquid.glsl').write_text(liquid, encoding='utf-8')
    wrapper = '''
vec4 mainImage(vec2 uv01) {
    Uniforms u = orbUniforms();
    vec4 c = orbGlassLiquidAnim(uv01, u);
    vec2 fc = vec2(uv01.x, 1.0-uv01.y)*u.size;
    vec2 uv = (2.0*fc-u.size)/max(min(u.size.x,u.size.y),1.0);
    float contourRad = max(u.radius,0.05)*glsContourScale(uv,u.time*u.speed,u.contourDeform,u);
    vec2 q = (2.0*fc-u.size)/u.size;
    float feather = 2.0/max(min(u.size.x,u.size.y),1.0);
    float start = min(mix(contourRad,1.0,0.5),1.0-feather);
    c *= 1.0-smoothstep(start,1.0,max(abs(q.x),abs(q.y)));
    return vec4(c.a > 0.00001 ? c.rgb/c.a : vec3(0), c.a);
}
'''
    (output / 'orb-presets.glsl').write_text(NOTICE+'#include "orb-liquid.glsl"\n'+wrapper, encoding='utf-8')
    particle_helpers = convert(metal[metal.index('constant uint PR_U_SEGMENTS'):metal.index('struct ribbon_vs_mainOutput')])
    vertex = metal[metal.index('    const metal::float2 corners[6]'):metal.index('struct ribbon_fs_mainOutput')]
    vertex = vertex[:vertex.rindex('    return out;')]
    vertex = convert(vertex)
    vertex = re.sub(r'const vec2 corners\[6\] = \{(.*?)\};', r'const vec2 corners[6] = vec2[6](\1);', vertex, flags=re.S)
    vertex = vertex.replace('ribbon_vs_mainOutput out;', '').replace('out.pos', 'gl_Position').replace('out.local', 'prLocal').replace('out.color', 'prColor').replace('out.opacity', 'prOpacity')
    # Vulkan viewport Y is down; OpenGL framebuffer Y is up.
    vertex += '\n#ifdef SATURN_VULKAN\n    gl_Position.y = -gl_Position.y;\n#endif\n}\n'
    varyings = 'SATURN_LOCATION(0) noperspective OUT vec2 prLocal;\nSATURN_LOCATION(1) OUT vec3 prColor;\nSATURN_LOCATION(2) OUT float prOpacity;\n'
    vs = common+particle_helpers+varyings.replace('OUT', 'out')+'\nvoid main(){\nUniforms u=orbUniforms();\nuint vertexIndex=uint(SATURN_VERTEX_ID), instanceIndex=uint(SATURN_INSTANCE_ID);\n'+vertex
    (output / 'orb-ribbons.vert').write_text(vs, encoding='utf-8')
    fragment = metal[metal.index('    float distanceSquared = metal::dot(in.local'):metal.index('metal::float2 prTextureUvFromOrb')]
    fragment = fragment[:fragment.rindex('}')]
    fragment = convert(fragment).replace('discard_fragment()', 'discard').replace('in.local', 'prLocal').replace('in.color', 'prColor').replace('in.opacity', 'prOpacity')
    fragment = fragment.replace('return ribbon_fs_mainOutput { vec4(color * alpha, alpha) };', 'frag = vec4(color * alpha, alpha);')
    fs = common+varyings.replace('OUT','in')+'SATURN_LOCATION(0) out vec4 frag;\nvoid main(){\nUniforms u=orbUniforms();\n'+fragment+'}\n'
    (output / 'orb-ribbons.frag').write_text(fs, encoding='utf-8')
    composite = convert(metal[metal.index('metal::float2 prTextureUvFromOrb'):])
    composite = re.sub(r'struct ribbon_composite_fs_mainOutput \{.*?\};', '', composite, flags=re.S)
    composite = re.sub(r'fragment ribbon_composite_fs_mainOutput ribbon_composite_fs_main\(.*?\) \{.*?float4 direct', 'vec4 orbComposite(vec2 uv01, Uniforms u) {\n vec4 direct', composite, flags=re.S)
    # vec4 conversion precedes the entry-point replacement.
    if 'ribbon_composite_fs_main(' in composite:
        composite = re.sub(r'fragment ribbon_composite_fs_mainOutput ribbon_composite_fs_main\(.*?\) \{.*?vec4 direct', 'vec4 orbComposite(vec2 uv01, Uniforms u) {\n vec4 direct', composite, flags=re.S)
    composite = composite.replace('in.uv','uv01')
    composite = re.sub(r'ribbonTexture.sample\(\s*ribbonSampler,\s*', 'saturnSampleBuffer(', composite)
    composite = re.sub(r'return ribbon_composite_fs_mainOutput \{(.*?)\};', r'return \1;', composite, flags=re.S)
    composite += '\nvec4 mainImage(vec2 uv) { vec4 c=orbComposite(uv,orbUniforms()); return vec4(c.a>0.00001?c.rgb/c.a:vec3(0),clamp(c.a,0.0,1.0)); }\n'
    (output / 'orb-particles.glsl').write_text(NOTICE+'#include "orb-liquid.glsl"\n'+composite, encoding='utf-8')
    presets = (source/'src/presets.ts').read_text(encoding='utf-8')
    def properties(block):
        result = {}
        for key, value in re.findall(r'(\w+):\s*("[^"]*"|true|false|-?[\d.]+)\s*,', block):
            result[key] = json.loads(value)
        return result
    base = properties(re.search(r'const basePreset[^=]*= \{(.*?)\};', presets, re.S)[1])
    blocks = dict(re.findall(r'(\w+): \{\s*\.\.\.basePreset,(.*?)\n  \}', presets, re.S))
    result = []
    for key, label, index in LABELS:
        params = {**base, **properties(blocks[key]), 'style': index, 'paletteCount': 0}
        for i, color in enumerate(('F7FBFF','EFF6FD','E0EEF9','D4E6F7','BBD5F3','A6C7F0','87B0EB',*(['6F9EE8']*5))):
            params[f'paletteStop{i}'] = '#'+color
        result.append({'id':key,'name':label,'uniforms':params})
    (output/'orb-presets.json').write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8')
    for name in ('orb-liquid.glsl','orb-presets.glsl','orb-particles.glsl','orb-ribbons.vert','orb-ribbons.frag'):
        path = output/name
        text = '\n'.join(line.rstrip() for line in path.read_text(encoding='utf-8').splitlines()).rstrip()+'\n'
        path.write_text(text,encoding='utf-8')
    print('Generated 13 presets and GPU particle stages')


if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source',type=Path,required=True)
    generate(parser.parse_args().source)
